#!/bin/sh

case ${1} in
    intro-ja.texi)
	perl -pe 's/\@chapter Introduction/\@chapter イントロダクション/' -i intro-ja.texi;
	perl -pe 's/\@section Caveats/\@section 注意事項/' -i intro-ja.texi;
	perl -pe 's/\@section Lisp History/\@section Lispの歴史/' -i intro-ja.texi;
	perl -pe 's/\@section Conventions/\@section 表記について/' -i intro-ja.texi;
	perl -pe 's/\@subsection Some Terms/\@subsection 用語について/' -i intro-ja.texi;
	perl -pe 's/\@subsection \@code\{nil\} and \@code\{t\}/\@subsection \@code\{nil\}と\@code\{t\}/' -i intro-ja.texi;
	perl -pe 's/\@subsection Evaluation Notation/\@subsection 評価の表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Printing Notation/\@subsection プリントの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Error Messages/\@subsection エラーメッセージ/' -i intro-ja.texi;
	perl -pe 's/\@subsection Buffer Text Notation/\@subsection バッファーテキストの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Format of Descriptions/\@subsection 説明のフォーマット/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Function Description/\@subsubsection 関数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Variable Description/\@subsubsection 変数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@section Version Information/\@section バージョンの情報/' -i intro-ja.texi;
	perl -pe 's/\@section Acknowledgments/\@section 謝辞/' -i intro-ja.texi;
	;;
    objects-ja.texi)
	perl -pe 's/\@chapter Lisp Data Types/\@chapter Lispのデータ型/' -i objects-ja.texi;
	perl -pe 's/\@section Printed Representation and Read Syntax/\@section プリント表現と読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Comments/\@section コメント/' -i objects-ja.texi;
	perl -pe 's/\@section Programming Types/\@section プログラミングの型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Integer Type/\@subsection 整数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Floating-Point Type/\@subsection 浮動小数点数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Character Type/\@subsection 文字型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Basic Char Syntax/\@subsubsection 基本的な文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection General Escape Syntax/\@subsubsection 一般的なエスケープ構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Control-Character Syntax/\@subsubsection コントロール文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Meta-Character Syntax/\@subsubsection メタ文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Other Character Modifier Bits/\@subsubsection その他の文字修飾ビット/' -i objects-ja.texi;
	perl -pe 's/\@subsection Symbol Type/\@subsection シンボル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Sequence Types/\@subsection シーケンス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Cons Cell and List Types/\@subsection コンスセルとリスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Drawing Lists as Box Diagrams/\@subsubsection ボックスダイアグラムとしてのリストの描写/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Dotted Pair Notation/\@subsubsection ドットペア表記/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Association List Type/\@subsubsection 連想リスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Array Type/\@subsection 配列型/' -i objects-ja.texi;
	perl -pe 's/\@subsection String Type/\@subsection 文字列型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Syntax for Strings/\@subsubsection 文字列の構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Non-\@acronym\{ASCII\} Characters in Strings/\@subsubsection 文字列内の非\@acronym\{ASCII\}文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Nonprinting Characters in Strings/\@subsubsection 文字列内の非プリント文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Text Properties in Strings/\@subsubsection 文字列内のテキストプロパティ/' -i objects-ja.texi;
	perl -pe 's/\@subsection Vector Type/\@subsection ベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Char-Table Type/\@subsection 文字テーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Bool-Vector Type/\@subsection ブールベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Hash Table Type/\@subsection ハッシュテーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Function Type/\@subsection 関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Macro Type/\@subsection マクロ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Primitive Function Type/\@subsection プリミティブ関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Byte-Code Function Type/\@subsection バイトコード関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Autoload Type/\@subsection autoload型/' -i objects-ja.texi;
	perl -pe 's/\@section Editing Types/\@section 編集用の型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Buffer Type/\@subsection バッファー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Marker Type/\@subsection マーカー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Type/\@subsection ウィンドウ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Type/\@subsection フレーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Terminal Type/\@subsection 端末型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Configuration Type/\@subsection ウィンドウ構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Configuration Type/\@subsection フレーム構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Process Type/\@subsection プロセス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Stream Type/\@subsection ストリーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Keymap Type/\@subsection キーマップ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Overlay Type/\@subsection オーバーレイ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Font Type/\@subsection フォント型/' -i objects-ja.texi;
	perl -pe 's/\@section Read Syntax for Circular Objects/\@section 循環オブジェクトの読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Type Predicates/\@section 型のための述語/' -i objects-ja.texi;
	perl -pe 's/\@section Equality Predicates/\@section 同等性のための述語/' -i objects-ja.texi;
	;;
    numbers-ja.texi)
	perl -pe 's/\@chapter Numbers/\@chapter 数値/' -i numbers-ja.texi;
	perl -pe 's/\@section Integer Basics/\@section 整数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Floating-Point Basics/\@section 浮動小数点数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Type Predicates for Numbers/\@section 数値のための述語/' -i numbers-ja.texi;
	perl -pe 's/\@section Comparison of Numbers/\@section 数値の比較/' -i numbers-ja.texi;
	perl -pe 's/\@section Numeric Conversions/\@section 数値の変換/' -i numbers-ja.texi;
	perl -pe 's/\@section Arithmetic Operations/\@section 算術演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Rounding Operations/\@section 丸め処理/' -i numbers-ja.texi;
	perl -pe 's/\@section Bitwise Operations on Integers/\@section 整数のビット演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Standard Mathematical Functions/\@section 標準的な数学関数/' -i numbers-ja.texi;
	perl -pe 's/\@section Random Numbers/\@section 乱数/' -i numbers-ja.texi;
	;;
    strings-ja.texi)
	perl -pe 's/\@chapter Strings and Characters/\@chapter 文字列と文字/' -i strings-ja.texi;
	perl -pe 's/\@section String and Character Basics/\@section 文字列と文字の基礎/' -i strings-ja.texi;
	perl -pe 's/\@section Predicates for Strings/\@section 文字列のための述語/' -i strings-ja.texi;
	perl -pe 's/\@section Creating Strings/\@section 文字列の作成/' -i strings-ja.texi;
	perl -pe 's/\@section Modifying Strings/\@section 文字列の変更/' -i strings-ja.texi;
	perl -pe 's/\@section Comparison of Characters and Strings/\@section 文字および文字列の比較/' -i strings-ja.texi;
	perl -pe 's/\@section Conversion of Characters and Strings/\@section 文字および文字列の変換/' -i strings-ja.texi;
	perl -pe 's/\@section Formatting Strings/\@section 文字列のフォーマット/' -i strings-ja.texi;
	perl -pe 's/\@section Case Conversion in Lisp/\@section Lispでの大文字小文字変換/' -i strings-ja.texi;
	perl -pe 's/\@section The Case Table/\@section caseテーブル/' -i strings-ja.texi;
	;;
    lists-ja.texi)
	perl -pe 's/\@chapter Lists/\@chapter リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Lists and Cons Cells/\@section リストとコンスセル/' -i lists-ja.texi;
	perl -pe 's/\@section Predicates on Lists/\@section リストのための述語/' -i lists-ja.texi;
	perl -pe 's/\@section Accessing Elements of Lists/\@section リスト要素へのアクセス/' -i lists-ja.texi;
	perl -pe 's/\@section Building Cons Cells and Lists/\@section コンスセルおよびリストの構築/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying List Variables/\@section リスト変数の変更/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying Existing List Structure/\@section 既存のリスト構造の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering List Elements with \@code\{setcar\}/\@subsection \@code\{setcar\}によるリスト要素の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering the CDR of a List/\@subsection リストのCDRの変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Functions that Rearrange Lists/\@subsection リストを再配置する関数/' -i lists-ja.texi;
	perl -pe 's/\@section Using Lists as Sets/\@section 集合としてのリストの使用/' -i lists-ja.texi;
	perl -pe 's/\@section Association Lists/\@section 連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Property Lists/\@section プロパティリスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists and Association Lists/\@subsection プロパティリストと連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists Outside Symbols/\@subsection プロパティリストと外部シンボル/' -i lists-ja.texi;
	;;
    sequences-ja.texi)
	perl -pe 's/\@chapter Sequences, Arrays, and Vectors/\@chapter シーケンス、配列、ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Sequences/\@section シーケンス/' -i sequences-ja.texi;
	perl -pe 's/\@section Arrays/\@section 配列/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions that Operate on Arrays/\@section 配列を操作する関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Vectors/\@section ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions for Vectors/\@section ベクターのための関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Char-Tables/\@section 文字テーブル/' -i sequences-ja.texi;
	perl -pe 's/\@section Bool-vectors/\@section ブールベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Managing a Fixed-Size Ring of Objects/\@section オブジェクト用固定長リングの管理/' -i sequences-ja.texi;
	;;
    hash-ja.texi)
	perl -pe 's/\@chapter Hash Tables/\@chapter ハッシュテーブル/' -i hash-ja.texi;
	perl -pe 's/\@section Creating Hash Tables/\@section ハッシュテーブルの作成/' -i hash-ja.texi;
	perl -pe 's/\@section Hash Table Access/\@section ハッシュテーブルへのアクセス/' -i hash-ja.texi;
	perl -pe 's/\@section Defining Hash Comparisons/\@section ハッシュの比較の定義/' -i hash-ja.texi;
	perl -pe 's/\@section Other Hash Table Functions/\@section ハッシュテーブルのためのその他関数/' -i hash-ja.texi;
	;;
    symbols-ja.texi)
	perl -pe 's/\@chapter Symbols/\@chapter シンボル/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Components/\@section シンボルの構成要素/' -i symbols-ja.texi;
	perl -pe 's/\@section Defining Symbols/\@section シンボルの定義/' -i symbols-ja.texi;
	perl -pe 's/\@section Creating and Interning Symbols/\@section シンボルの作成とintern/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Properties/\@section シンボルのプロパティ/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Accessing Symbol Properties/\@subsection シンボルのプロパティへのアクセス/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Standard Symbol Properties/\@subsection シンボルの標準的なプロパティ/' -i symbols-ja.texi;
	;;
    eval-ja.texi)
	perl -pe 's/\@chapter Evaluation/\@chapter 評価/' -i eval-ja.texi;
	perl -pe 's/\@section Introduction to Evaluation/\@section 評価の概要/' -i eval-ja.texi;
	perl -pe 's/\@section Kinds of Forms/\@section フォームの種類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Self-Evaluating Forms/\@subsection 自己評価を行うフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Forms/\@subsection シンボルのフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Classification of List Forms/\@subsection リストフォームの分類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Function Indirection/\@subsection シンボル関数インダイレクション/' -i eval-ja.texi;
	perl -pe 's/\@subsection Evaluation of Function Forms/\@subsection 関数フォームの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Lisp Macro Evaluation/\@subsection Lispマクロの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Special Forms/\@subsection スペシャルフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Autoloading/\@subsection 自動ロード/' -i eval-ja.texi;
	perl -pe 's/\@section Quoting/\@section クォート/' -i eval-ja.texi;
	perl -pe 's/\@section Backquote/\@section バッククォート/' -i eval-ja.texi;
	perl -pe 's/\@section Eval/\@section eval/' -i eval-ja.texi;
	;;
    control-ja.texi)
	perl -pe 's/\@chapter Control Structures/\@chapter 制御構造/' -i control-ja.texi;
	perl -pe 's/\@section Sequencing/\@section 順序/' -i control-ja.texi;
	perl -pe 's/\@section Conditionals/\@section 条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Pattern matching case statement/\@subsection パターンマッチングによるcase文/' -i control-ja.texi;
	perl -pe 's/\@section Constructs for Combining Conditions/\@section 条件の組み合わせ/' -i control-ja.texi;
	perl -pe 's/\@section Iteration/\@section 繰り返し/' -i control-ja.texi;
	perl -pe 's/\@section Nonlocal Exits/\@section 非ローカル脱出/' -i control-ja.texi;
	perl -pe 's/\@subsection Explicit Nonlocal Exits\: \@code\{catch\} and \@code\{throw\}/\@subsection 明示的な非ローカル脱出\: \@code\{catch\}と\@code\{throw\}/' -i control-ja.texi;
	perl -pe 's/\@subsection Examples of \@code\{catch\} and \@code\{throw\}/\@subsection \@code\{catch\}と\@code\{thrown\}の例/' -i control-ja.texi;
	perl -pe 's/\@subsection Errors/\@subsection エラー/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How to Signal an Error/\@subsubsection エラーをシグナルする方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How Emacs Processes Errors/\@subsubsection Emacsがエラーを処理する方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Writing Code to Handle Errors/\@subsubsection エラーを処理するコードの記述/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Error Symbols and Condition Names/\@subsubsection エラーシンボルとエラー条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Cleaning Up from Nonlocal Exits/\@subsection 非ローカル脱出のクリーンアップ/' -i control-ja.texi;
	;;
    variables-ja.texi)
	perl -pe 's/\@chapter Variables/\@chapter 変数/' -i variables-ja.texi;
	perl -pe 's/\@section Global Variables/\@section グローバル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Variables that Never Change/\@section 変更不可な変数/' -i variables-ja.texi;
	perl -pe 's/\@section Local Variables/\@section ローカル変数/' -i variables-ja.texi;
	perl -pe "s/\@section When a Variable is \`\`Void\'\'/\@section 変数が\`\`void\'\'のとき/" -i variables-ja.texi;
	perl -pe 's/\@section Defining Global Variables/\@section グローバル変数の定義/' -i variables-ja.texi;
	perl -pe 's/\@section Tips for Defining Variables Robustly/\@section 堅牢な変数定義のためのヒント/' -i variables-ja.texi;
	perl -pe 's/\@section Accessing Variable Values/\@section 変数の値へのアクセス/' -i variables-ja.texi;
	perl -pe 's/\@section Setting Variable Values/\@section 変数の値のセット/' -i variables-ja.texi;
	perl -pe 's/\@section Scoping Rules for Variable Bindings/\@section 変数のバインディングのスコーピングルール/' -i variables-ja.texi;
	perl -pe 's/\@subsection Dynamic Binding/\@subsection ダイナミックバインディング/' -i variables-ja.texi;
	perl -pe 's/\@subsection Proper Use of Dynamic Binding/\@subsection ダイナミックバインディングの正しい使用/' -i variables-ja.texi;
	perl -pe 's/\@subsection Lexical Binding/\@subsection レキシカルバインディング/' -i variables-ja.texi;
	perl -pe 's/\@subsection Using Lexical Binding/\@subsection レキシカルバインディングの使用/' -i variables-ja.texi;
	perl -pe 's/\@section Buffer-Local Variables/\@section バッファーローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@subsection Introduction to Buffer-Local Variables/\@subsection バッファーローカル変数の概要/' -i variables-ja.texi;
	perl -pe 's/\@subsection Creating and Deleting Buffer-Local Bindings/\@subsection バッファーローカルなバインディングの作成と削除/' -i variables-ja.texi;
	perl -pe 's/\@subsection The Default Value of a Buffer-Local Variable/\@subsection バッファーローカル変数のデフォルト値/' -i variables-ja.texi;
	perl -pe 's/\@section File Local Variables/\@section ファイルローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Directory Local Variables/\@section ディレクトリーローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Variable Aliases/\@section 変数のエイリアス/' -i variables-ja.texi;
	perl -pe 's/\@section Variables with Restricted Values/\@section 値を制限された変数/' -i variables-ja.texi;
	perl -pe 's/\@section Generalized Variables/\@section ジェネリック変数/' -i variables-ja.texi;
	perl -pe 's/\@subsection The \@code\{setf\} Macro/\@subsection \@code\{setf\}マクロ/' -i variables-ja.texi;
	perl -pe 's/\@subsection Defining new \@code\{setf\} forms/\@subsection 新たな\@code\{setf\}フォーム/' -i variables-ja.texi;
	;;
    functions-ja.texi)
	perl -pe 's/\@chapter Functions/\@chapter 関数/' -i functions-ja.texi;
	perl -pe 's/\@section What Is a Function\?/\@section 関数とは\?/' -i functions-ja.texi;
	perl -pe 's/\@section Lambda Expressions/\@section ラムダ式/' -i functions-ja.texi;
	perl -pe 's/\@subsection Components of a Lambda Expression/\@subsection ラムダ式の構成要素/' -i functions-ja.texi;
	perl -pe 's/\@subsection A Simple Lambda Expression Example/\@subsection 単純なラムダ式の例/' -i functions-ja.texi;
	perl -pe 's/\@subsection Other Features of Argument Lists/\@subsection 引数リストのその他機能/' -i functions-ja.texi;
	perl -pe 's/\@subsection Documentation Strings of Functions/\@subsection 関数のドキュメント文字列/' -i functions-ja.texi;
	perl -pe 's/\@section Naming a Function/\@section 関数の命名/' -i functions-ja.texi;
	perl -pe 's/\@section Defining Functions/\@section 関数の定義/' -i functions-ja.texi;
	perl -pe 's/\@section Calling Functions/\@section 関数の呼び出し/' -i functions-ja.texi;
	perl -pe 's/\@section Mapping Functions/\@section 関数のマッピング/' -i functions-ja.texi;
	perl -pe 's/\@section Anonymous Functions/\@section 無名関数/' -i functions-ja.texi;
	perl -pe 's/\@section Accessing Function Cell Contents/\@section 関数セルの内容へのアクセス/' -i functions-ja.texi;
	perl -pe 's/\@section Closures/\@section クロージャー/' -i functions-ja.texi;
	perl -pe 's/\@section Advising Emacs Lisp Functions/\@section Emacs Lisp関数にたいするアドバイス/' -i functions-ja.texi;
	perl -pe 's/\@subsection Primitives to manipulate advices/\@subsection アドバイスを操作するためのプリミティブ/' -i functions-ja.texi;
	perl -pe 's/\@subsection Advising Named Functions/\@subsection 名前つき関数にたいするアドバイス/' -i functions-ja.texi;
	perl -pe 's/\@subsection Ways to compose advices/\@subsection アドバイスの構築方法/' -i functions-ja.texi;
	perl -pe 's/\@subsection Adapting code using the old defadvice/\@subsection 古いdefadviceを使用するコードの改良/' -i functions-ja.texi;
	perl -pe 's/\@section Declaring Functions Obsolete/\@section 関数を陳腐と宣言する/' -i functions-ja.texi;
	perl -pe 's/\@section Inline Functions/\@section インライン関数Inline Functions/' -i functions-ja.texi;
	perl -pe 's/\@section The \@code\{declare\} Form/\@section \@code\{declare\}フォーム/' -i functions-ja.texi;
	perl -pe 's/\@section Telling the Compiler that a Function is Defined/\@section コンパイラーへの定義済み関数の指示/' -i functions-ja.texi;
	perl -pe 's/\@section Determining whether a Function is Safe to Call/\@section 安全に関数を呼び出せるかどうかの判断/' -i functions-ja.texi;
	perl -pe 's/\@section Other Topics Related to Functions/\@section 関数に関するその他トピック/' -i functions-ja.texi;
	;;
    macros-ja.texi)
	perl -pe 's/\@chapter Macros/\@chapter マクロ/' -i macros-ja.texi;
	perl -pe 's/\@section A Simple Example of a Macro/\@section 単純なマクロの例/' -i macros-ja.texi;
	perl -pe 's/\@section Expansion of a Macro Call/\@section マクロ呼び出しの展開/' -i macros-ja.texi;
	perl -pe 's/\@section Macros and Byte Compilation/\@section マクロとバイトコンパイル/' -i macros-ja.texi;
	perl -pe 's/\@section Defining Macros/\@section マクロの定義/' -i macros-ja.texi;
	perl -pe 's/\@section Common Problems Using Macros/\@section マクロ使用に関する一般的な問題/' -i macros-ja.texi;
	perl -pe 's/\@subsection Wrong Time/\@subsection タイミング間違い/' -i macros-ja.texi;
	perl -pe 's/\@subsection Evaluating Macro Arguments Repeatedly/\@subsection マクロ引数の多重評価/' -i macros-ja.texi;
	perl -pe 's/\@subsection Local Variables in Macro Expansions/\@subsection マクロ展開でのローカル変数/' -i macros-ja.texi;
	perl -pe 's/\@subsection Evaluating Macro Arguments in Expansion/\@subsection 展開におけるマクロ引数の評価/' -i macros-ja.texi;
	perl -pe 's/\@subsection How Many Times is the Macro Expanded\?/\@subsection マクロが展開される回数は\?/' -i macros-ja.texi;
	perl -pe 's/\@section Indenting Macros/\@section マクロのインデント/' -i macros-ja.texi;
	;;
    customize-ja.texi)
	perl -pe 's/\@chapter Customization Settings/\@chapter カスタマイズ設定/' -i customize-ja.texi;
	perl -pe 's/\@section Common Item Keywords/\@section 一般的なキーワードアイテム/' -i customize-ja.texi;
	perl -pe 's/\@section Defining Customization Groups/\@section カスタマイズグループの定義/' -i customize-ja.texi;
	perl -pe 's/\@section Defining Customization Variables/\@section カスタマイズ変数の定義/' -i customize-ja.texi;
	perl -pe 's/\@section Customization Types/\@section カスタマイズ型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Simple Types/\@subsection 単純型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Composite Types/\@subsection 複合型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Splicing into Lists/\@subsection リストへのスプライス/' -i customize-ja.texi;
	perl -pe 's/\@subsection Type Keywords/\@subsection 型キーワード/' -i customize-ja.texi;
	perl -pe 's/\@subsection Defining New Types/\@subsection 新たな型の定義/' -i customize-ja.texi;
	perl -pe 's/\@section Applying Customizations/\@section カスタマイズの適用/' -i customize-ja.texi;
	perl -pe 's/\@section Custom Themes/\@section カスタムテーマ/' -i customize-ja.texi;
	;;
    loading-ja.texi)
	perl -pe 's/\@chapter Loading/\@chapter ロード/' -i loading-ja.texi;
	perl -pe 's/\@section How Programs Do Loading/\@section プログラムがロードを行う方法/' -i loading-ja.texi;
	perl -pe 's/\@section Load Suffixes/\@section ロードでの拡張子/' -i loading-ja.texi;
	perl -pe 's/\@section Library Search/\@section ライブラリー検索/' -i loading-ja.texi;
	perl -pe 's/\@section Loading Non-\@acronym\{ASCII\} Characters/\@section 非\@acronym\{ASCII\}文字のロード/' -i loading-ja.texi;
	perl -pe 's/\@section Autoload/\@section autoload/' -i loading-ja.texi;
	perl -pe 's/\@section Repeated Loading/\@section 多重ロード/' -i loading-ja.texi;
	perl -pe 's/\@section Features/\@section 名前つき機能/' -i loading-ja.texi;
	perl -pe 's/\@section Which File Defined a Certain Symbol/\@section どのファイルで特定のシンボルが定義されているか/' -i loading-ja.texi;
	perl -pe 's/\@section Unloading/\@section アンロード/' -i loading-ja.texi;
	perl -pe 's/\@section Hooks for Loading/\@section ロードのためのフック/' -i loading-ja.texi;
	;;
    *)
	printf "Not subject to replace : %s\n" ${1};
	;;
esac
