#!/bin/sh

case ${1} in
    intro-ja.texi)
	perl -pe 's/\@chapter Introduction/\@chapter イントロダクション/' -i intro-ja.texi;
	perl -pe 's/\@section Caveats/\@section 注意事項/' -i intro-ja.texi;
	perl -pe 's/\@section Lisp History/\@section Lispの歴史/' -i intro-ja.texi;
	perl -pe 's/\@section Conventions/\@section 表記について/' -i intro-ja.texi;
	perl -pe 's/\@subsection Some Terms/\@subsection 用語について/' -i intro-ja.texi;
	perl -pe 's/\@subsection \@code\{nil\} and \@code\{t\}/\@subsection \@code\{nil\}と\@code\{t\}/' -i intro-ja.texi;
	perl -pe 's/\@subsection Evaluation Notation/\@subsection 評価の表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Printing Notation/\@subsection プリントの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Error Messages/\@subsection エラーメッセージ/' -i intro-ja.texi;
	perl -pe 's/\@subsection Buffer Text Notation/\@subsection バッファーテキストの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Format of Descriptions/\@subsection 説明のフォーマット/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Function Description/\@subsubsection 関数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Variable Description/\@subsubsection 変数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@section Version Information/\@section バージョンの情報/' -i intro-ja.texi;
	perl -pe 's/\@section Acknowledgments/\@section 謝辞/' -i intro-ja.texi;
	;;
    objects-ja.texi)
	perl -pe 's/\@chapter Lisp Data Types/\@chapter Lispのデータ型/' -i objects-ja.texi;
	perl -pe 's/\@section Printed Representation and Read Syntax/\@section プリント表現と読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Comments/\@section コメント/' -i objects-ja.texi;
	perl -pe 's/\@section Programming Types/\@section プログラミングの型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Integer Type/\@subsection 整数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Floating-Point Type/\@subsection 浮動小数点数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Character Type/\@subsection 文字型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Basic Char Syntax/\@subsubsection 基本的な文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection General Escape Syntax/\@subsubsection 一般的なエスケープ構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Control-Character Syntax/\@subsubsection コントロール文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Meta-Character Syntax/\@subsubsection メタ文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Other Character Modifier Bits/\@subsubsection その他の文字修飾ビット/' -i objects-ja.texi;
	perl -pe 's/\@subsection Symbol Type/\@subsection シンボル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Sequence Types/\@subsection シーケンス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Cons Cell and List Types/\@subsection コンスセルとリスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Drawing Lists as Box Diagrams/\@subsubsection ボックスダイアグラムとしてのリストの描写/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Dotted Pair Notation/\@subsubsection ドットペア表記/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Association List Type/\@subsubsection 連想リスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Array Type/\@subsection 配列型/' -i objects-ja.texi;
	perl -pe 's/\@subsection String Type/\@subsection 文字列型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Syntax for Strings/\@subsubsection 文字列の構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Non-\@acronym\{ASCII\} Characters in Strings/\@subsubsection 文字列内の非\@acronym\{ASCII\}文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Nonprinting Characters in Strings/\@subsubsection 文字列内の非プリント文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Text Properties in Strings/\@subsubsection 文字列内のテキストプロパティ/' -i objects-ja.texi;
	perl -pe 's/\@subsection Vector Type/\@subsection ベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Char-Table Type/\@subsection 文字テーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Bool-Vector Type/\@subsection ブールベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Hash Table Type/\@subsection ハッシュテーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Function Type/\@subsection 関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Macro Type/\@subsection マクロ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Primitive Function Type/\@subsection プリミティブ関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Byte-Code Function Type/\@subsection バイトコード関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Autoload Type/\@subsection autoload型/' -i objects-ja.texi;
	perl -pe 's/\@section Editing Types/\@section 編集用の型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Buffer Type/\@subsection バッファー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Marker Type/\@subsection マーカー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Type/\@subsection ウィンドウ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Type/\@subsection フレーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Terminal Type/\@subsection 端末型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Configuration Type/\@subsection ウィンドウ構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Configuration Type/\@subsection フレーム構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Process Type/\@subsection プロセス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Stream Type/\@subsection ストリーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Keymap Type/\@subsection キーマップ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Overlay Type/\@subsection オーバーレイ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Font Type/\@subsection フォント型/' -i objects-ja.texi;
	perl -pe 's/\@section Read Syntax for Circular Objects/\@section 循環オブジェクトの読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Type Predicates/\@section 型のための述語/' -i objects-ja.texi;
	perl -pe 's/\@section Equality Predicates/\@section 同等性のための述語/' -i objects-ja.texi;
	;;
    numbers-ja.texi)
	perl -pe 's/\@chapter Numbers/\@chapter 数値/' -i numbers-ja.texi;
	perl -pe 's/\@section Integer Basics/\@section 整数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Floating-Point Basics/\@section 浮動小数点数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Type Predicates for Numbers/\@section 数値のための述語/' -i numbers-ja.texi;
	perl -pe 's/\@section Comparison of Numbers/\@section 数値の比較/' -i numbers-ja.texi;
	perl -pe 's/\@section Numeric Conversions/\@section 数値の変換/' -i numbers-ja.texi;
	perl -pe 's/\@section Arithmetic Operations/\@section 算術演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Rounding Operations/\@section 丸め処理/' -i numbers-ja.texi;
	perl -pe 's/\@section Bitwise Operations on Integers/\@section 整数のビット演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Standard Mathematical Functions/\@section 標準的な数学関数/' -i numbers-ja.texi;
	perl -pe 's/\@section Random Numbers/\@section 乱数/' -i numbers-ja.texi;
	;;
    strings-ja.texi)
	perl -pe 's/\@chapter Strings and Characters/\@chapter 文字列と文字/' -i strings-ja.texi;
	perl -pe 's/\@section String and Character Basics/\@section 文字列と文字の基礎/' -i strings-ja.texi;
	perl -pe 's/\@section Predicates for Strings/\@section 文字列のための述語/' -i strings-ja.texi;
	perl -pe 's/\@section Creating Strings/\@section 文字列の作成/' -i strings-ja.texi;
	perl -pe 's/\@section Modifying Strings/\@section 文字列の変更/' -i strings-ja.texi;
	perl -pe 's/\@section Comparison of Characters and Strings/\@section 文字および文字列の比較/' -i strings-ja.texi;
	perl -pe 's/\@section Conversion of Characters and Strings/\@section 文字および文字列の変換/' -i strings-ja.texi;
	perl -pe 's/\@section Formatting Strings/\@section 文字列のフォーマット/' -i strings-ja.texi;
	perl -pe 's/\@section Case Conversion in Lisp/\@section Lispでの大文字小文字変換/' -i strings-ja.texi;
	perl -pe 's/\@section The Case Table/\@section caseテーブル/' -i strings-ja.texi;
	;;
    lists-ja.texi)
	perl -pe 's/\@chapter Lists/\@chapter リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Lists and Cons Cells/\@section リストとコンスセル/' -i lists-ja.texi;
	perl -pe 's/\@section Predicates on Lists/\@section リストのための述語/' -i lists-ja.texi;
	perl -pe 's/\@section Accessing Elements of Lists/\@section リスト要素へのアクセス/' -i lists-ja.texi;
	perl -pe 's/\@section Building Cons Cells and Lists/\@section コンスセルおよびリストの構築/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying List Variables/\@section リスト変数の変更/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying Existing List Structure/\@section 既存のリスト構造の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering List Elements with \@code\{setcar\}/\@subsection \@code\{setcar\}によるリスト要素の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering the CDR of a List/\@subsection リストのCDRの変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Functions that Rearrange Lists/\@subsection リストを再配置する関数/' -i lists-ja.texi;
	perl -pe 's/\@section Using Lists as Sets/\@section 集合としてのリストの使用/' -i lists-ja.texi;
	perl -pe 's/\@section Association Lists/\@section 連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Property Lists/\@section プロパティリスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists and Association Lists/\@subsection プロパティリストと連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists Outside Symbols/\@subsection プロパティリストと外部シンボル/' -i lists-ja.texi;
	;;
    sequences-ja.texi)
	perl -pe 's/\@chapter Sequences, Arrays, and Vectors/\@chapter シーケンス、配列、ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Sequences/\@section シーケンス/' -i sequences-ja.texi;
	perl -pe 's/\@section Arrays/\@section 配列/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions that Operate on Arrays/\@section 配列を操作する関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Vectors/\@section ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions for Vectors/\@section ベクターのための関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Char-Tables/\@section 文字テーブル/' -i sequences-ja.texi;
	perl -pe 's/\@section Bool-vectors/\@section ブールベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Managing a Fixed-Size Ring of Objects/\@section オブジェクト用固定長リングの管理/' -i sequences-ja.texi;
	;;
    hash-ja.texi)
	perl -pe 's/\@chapter Hash Tables/\@chapter ハッシュテーブル/' -i hash-ja.texi;
	perl -pe 's/\@section Creating Hash Tables/\@section ハッシュテーブルの作成/' -i hash-ja.texi;
	perl -pe 's/\@section Hash Table Access/\@section ハッシュテーブルへのアクセス/' -i hash-ja.texi;
	perl -pe 's/\@section Defining Hash Comparisons/\@section ハッシュの比較の定義/' -i hash-ja.texi;
	perl -pe 's/\@section Other Hash Table Functions/\@section ハッシュテーブルのためのその他関数/' -i hash-ja.texi;
	;;
    symbols-ja.texi)
	perl -pe 's/\@chapter Symbols/\@chapter シンボル/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Components/\@section シンボルの構成要素/' -i symbols-ja.texi;
	perl -pe 's/\@section Defining Symbols/\@section シンボルの定義/' -i symbols-ja.texi;
	perl -pe 's/\@section Creating and Interning Symbols/\@section シンボルの作成とintern/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Properties/\@section シンボルのプロパティ/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Accessing Symbol Properties/\@subsection シンボルのプロパティへのアクセス/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Standard Symbol Properties/\@subsection シンボルの標準的なプロパティ/' -i symbols-ja.texi;
	;;
    eval-ja.texi)
	perl -pe 's/\@chapter Evaluation/\@chapter 評価/' -i eval-ja.texi;
	perl -pe 's/\@section Introduction to Evaluation/\@section 評価の概要/' -i eval-ja.texi;
	perl -pe 's/\@section Kinds of Forms/\@section フォームの種類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Self-Evaluating Forms/\@subsection 自己評価を行うフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Forms/\@subsection シンボルのフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Classification of List Forms/\@subsection リストフォームの分類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Function Indirection/\@subsection シンボル関数インダイレクション/' -i eval-ja.texi;
	perl -pe 's/\@subsection Evaluation of Function Forms/\@subsection 関数フォームの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Lisp Macro Evaluation/\@subsection Lispマクロの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Special Forms/\@subsection スペシャルフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Autoloading/\@subsection 自動ロード/' -i eval-ja.texi;
	perl -pe 's/\@section Quoting/\@section クォート/' -i eval-ja.texi;
	perl -pe 's/\@section Backquote/\@section バッククォート/' -i eval-ja.texi;
	perl -pe 's/\@section Eval/\@section eval/' -i eval-ja.texi;
	;;
    control-ja.texi)
	perl -pe 's/\@chapter Control Structures/\@chapter 制御構造/' -i control-ja.texi;
	perl -pe 's/\@section Sequencing/\@section 順序/' -i control-ja.texi;
	perl -pe 's/\@section Conditionals/\@section 条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Pattern matching case statement/\@subsection パターンマッチングによるcase文/' -i control-ja.texi;
	perl -pe 's/\@section Constructs for Combining Conditions/\@section 条件の組み合わせ/' -i control-ja.texi;
	perl -pe 's/\@section Iteration/\@section 繰り返し/' -i control-ja.texi;
	perl -pe 's/\@section Nonlocal Exits/\@section 非ローカル脱出/' -i control-ja.texi;
	perl -pe 's/\@subsection Explicit Nonlocal Exits\: \@code\{catch\} and \@code\{throw\}/\@subsection 明示的な非ローカル脱出\: \@code\{catch\}と\@code\{throw\}/' -i control-ja.texi;
	perl -pe 's/\@subsection Examples of \@code\{catch\} and \@code\{throw\}/\@subsection \@code\{catch\}と\@code\{throw\n}の例/' -i control-ja.texi;
	perl -pe 's/\@subsection Errors/\@subsection エラー/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How to Signal an Error/\@subsubsection エラーをシグナルする方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How Emacs Processes Errors/\@subsubsection Emacsがエラーを処理する方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Writing Code to Handle Errors/\@subsubsection エラーを処理するコードの記述/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Error Symbols and Condition Names/\@subsubsection エラーシンボルとエラー条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Cleaning Up from Nonlocal Exits/\@subsection 非ローカル脱出のクリーンアップ/' -i control-ja.texi;
	;;
    variables-ja.texi)
	perl -pe 's/\@chapter Variables/\@chapter Variables/' -i variables-ja.texi;
	perl -pe 's/\@section Global Variables/\@section Global Variables/' -i variables-ja.texi;
	perl -pe 's/\@section Variables that Never Change/\@section Variables that Never Change/' -i variables-ja.texi;
	perl -pe 's/\@section Local Variables/\@section Local Variables/' -i variables-ja.texi;
	perl -pe 's/\@section When a Variable is ``Void''/\@section When a Variable is ``Void''/' -i variables-ja.texi;
	perl -pe 's/\@section Defining Global Variables/\@section Defining Global Variables/' -i variables-ja.texi;
	perl -pe 's/\@section Tips for Defining Variables Robustly/\@section Tips for Defining Variables Robustly/' -i variables-ja.texi;
	perl -pe 's/\@section Accessing Variable Values/\@section Accessing Variable Values/' -i variables-ja.texi;
	perl -pe 's/\@section Setting Variable Values/\@section Setting Variable Values/' -i variables-ja.texi;
	perl -pe 's/\@section Scoping Rules for Variable Bindings/\@section Scoping Rules for Variable Bindings/' -i variables-ja.texi;
	perl -pe 's/\@subsection Dynamic Binding/\@subsection Dynamic Binding/' -i variables-ja.texi;
	perl -pe 's/\@subsection Proper Use of Dynamic Binding/\@subsection Proper Use of Dynamic Binding/' -i variables-ja.texi;
	perl -pe 's/\@subsection Lexical Binding/\@subsection Lexical Binding/' -i variables-ja.texi;
	perl -pe 's/\@subsection Using Lexical Binding/\@subsection Using Lexical Binding/' -i variables-ja.texi;
	perl -pe 's/\@section Buffer-Local Variables/\@section Buffer-Local Variables/' -i variables-ja.texi;
	perl -pe 's/\@subsection Introduction to Buffer-Local Variables/\@subsection Introduction to Buffer-Local Variables/' -i variables-ja.texi;
	perl -pe 's/\@subsection Creating and Deleting Buffer-Local Bindings/\@subsection Creating and Deleting Buffer-Local Bindings/' -i variables-ja.texi;
	perl -pe 's/\@subsection The Default Value of a Buffer-Local Variable/\@subsection The Default Value of a Buffer-Local Variable/' -i variables-ja.texi;
	perl -pe 's/\@section File Local Variables/\@section File Local Variables/' -i variables-ja.texi;
	perl -pe 's/\@section Directory Local Variables/\@section Directory Local Variables/' -i variables-ja.texi;
	perl -pe 's/\@section Variable Aliases/\@section Variable Aliases/' -i variables-ja.texi;
	perl -pe 's/\@section Variables with Restricted Values/\@section Variables with Restricted Values/' -i variables-ja.texi;
	perl -pe 's/\@section Generalized Variables/\@section Generalized Variables/' -i variables-ja.texi;
	perl -pe 's/\@subsection The @code{setf} Macro/\@subsection The @code{setf} Macro/' -i variables-ja.texi;
	perl -pe 's/\@subsection Defining new @code{setf} forms/\@subsection Defining new @code{setf} forms/' -i variables-ja.texi;
	;;
    *)
	printf "Not subject to replace : %s\n" ${1};
	;;
esac
