#!/bin/sh

case ${1} in
    intro-ja.texi)
	perl -pe 's/\@chapter Introduction/\@chapter イントロダクション/' -i intro-ja.texi;
	perl -pe 's/\@section Caveats/\@section 注意事項/' -i intro-ja.texi;
	perl -pe 's/\@section Lisp History/\@section Lispの歴史/' -i intro-ja.texi;
	perl -pe 's/\@section Conventions/\@section 表記について/' -i intro-ja.texi;
	perl -pe 's/\@subsection Some Terms/\@subsection 用語について/' -i intro-ja.texi;
	perl -pe 's/\@subsection \@code\{nil\} and \@code\{t\}/\@subsection \@code\{nil\}と\@code\{t\}/' -i intro-ja.texi;
	perl -pe 's/\@subsection Evaluation Notation/\@subsection 評価の表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Printing Notation/\@subsection プリントの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Error Messages/\@subsection エラーメッセージ/' -i intro-ja.texi;
	perl -pe 's/\@subsection Buffer Text Notation/\@subsection バッファーテキストの表記/' -i intro-ja.texi;
	perl -pe 's/\@subsection Format of Descriptions/\@subsection 説明のフォーマット/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Function Description/\@subsubsection 関数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@subsubsection A Sample Variable Description/\@subsubsection 変数の説明例/' -i intro-ja.texi;
	perl -pe 's/\@section Version Information/\@section バージョンの情報/' -i intro-ja.texi;
	perl -pe 's/\@section Acknowledgments/\@section 謝辞/' -i intro-ja.texi;
	;;
    objects-ja.texi)
	perl -pe 's/\@chapter Lisp Data Types/\@chapter Lispのデータ型/' -i objects-ja.texi;
	perl -pe 's/\@section Printed Representation and Read Syntax/\@section プリント表現と読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Comments/\@section コメント/' -i objects-ja.texi;
	perl -pe 's/\@section Programming Types/\@section プログラミングの型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Integer Type/\@subsection 整数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Floating-Point Type/\@subsection 浮動小数点数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Character Type/\@subsection 文字型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Basic Char Syntax/\@subsubsection 基本的な文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection General Escape Syntax/\@subsubsection 一般的なエスケープ構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Control-Character Syntax/\@subsubsection コントロール文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Meta-Character Syntax/\@subsubsection メタ文字構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Other Character Modifier Bits/\@subsubsection その他の文字修飾ビット/' -i objects-ja.texi;
	perl -pe 's/\@subsection Symbol Type/\@subsection シンボル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Sequence Types/\@subsection シーケンス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Cons Cell and List Types/\@subsection コンスセルとリスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Drawing Lists as Box Diagrams/\@subsubsection ボックスダイアグラムとしてのリストの描写/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Dotted Pair Notation/\@subsubsection ドットペア表記/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Association List Type/\@subsubsection 連想リスト型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Array Type/\@subsection 配列型/' -i objects-ja.texi;
	perl -pe 's/\@subsection String Type/\@subsection 文字列型/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Syntax for Strings/\@subsubsection 文字列の構文/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Non-\@acronym\{ASCII\} Characters in Strings/\@subsubsection 文字列内の非\@acronym\{ASCII\}文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Nonprinting Characters in Strings/\@subsubsection 文字列内の非プリント文字/' -i objects-ja.texi;
	perl -pe 's/\@subsubsection Text Properties in Strings/\@subsubsection 文字列内のテキストプロパティ/' -i objects-ja.texi;
	perl -pe 's/\@subsection Vector Type/\@subsection ベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Char-Table Type/\@subsection 文字テーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Bool-Vector Type/\@subsection ブールベクター型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Hash Table Type/\@subsection ハッシュテーブル型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Function Type/\@subsection 関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Macro Type/\@subsection マクロ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Primitive Function Type/\@subsection プリミティブ関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Byte-Code Function Type/\@subsection バイトコード関数型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Autoload Type/\@subsection autoload型/' -i objects-ja.texi;
	perl -pe 's/\@section Editing Types/\@section 編集用の型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Buffer Type/\@subsection バッファー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Marker Type/\@subsection マーカー型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Type/\@subsection ウィンドウ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Type/\@subsection フレーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Terminal Type/\@subsection 端末型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Window Configuration Type/\@subsection ウィンドウ構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Frame Configuration Type/\@subsection フレーム構成型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Process Type/\@subsection プロセス型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Stream Type/\@subsection ストリーム型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Keymap Type/\@subsection キーマップ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Overlay Type/\@subsection オーバーレイ型/' -i objects-ja.texi;
	perl -pe 's/\@subsection Font Type/\@subsection フォント型/' -i objects-ja.texi;
	perl -pe 's/\@section Read Syntax for Circular Objects/\@section 循環オブジェクトの読み取り構文/' -i objects-ja.texi;
	perl -pe 's/\@section Type Predicates/\@section 型のための述語/' -i objects-ja.texi;
	perl -pe 's/\@section Equality Predicates/\@section 同等性のための述語/' -i objects-ja.texi;
	;;
    numbers-ja.texi)
	perl -pe 's/\@chapter Numbers/\@chapter 数値/' -i numbers-ja.texi;
	perl -pe 's/\@section Integer Basics/\@section 整数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Floating-Point Basics/\@section 浮動小数点数の基礎/' -i numbers-ja.texi;
	perl -pe 's/\@section Type Predicates for Numbers/\@section 数値のための述語/' -i numbers-ja.texi;
	perl -pe 's/\@section Comparison of Numbers/\@section 数値の比較/' -i numbers-ja.texi;
	perl -pe 's/\@section Numeric Conversions/\@section 数値の変換/' -i numbers-ja.texi;
	perl -pe 's/\@section Arithmetic Operations/\@section 算術演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Rounding Operations/\@section 丸め処理/' -i numbers-ja.texi;
	perl -pe 's/\@section Bitwise Operations on Integers/\@section 整数のビット演算/' -i numbers-ja.texi;
	perl -pe 's/\@section Standard Mathematical Functions/\@section 標準的な数学関数/' -i numbers-ja.texi;
	perl -pe 's/\@section Random Numbers/\@section 乱数/' -i numbers-ja.texi;
	;;
    strings-ja.texi)
	perl -pe 's/\@chapter Strings and Characters/\@chapter 文字列と文字/' -i strings-ja.texi;
	perl -pe 's/\@section String and Character Basics/\@section 文字列と文字の基礎/' -i strings-ja.texi;
	perl -pe 's/\@section Predicates for Strings/\@section 文字列のための述語/' -i strings-ja.texi;
	perl -pe 's/\@section Creating Strings/\@section 文字列の作成/' -i strings-ja.texi;
	perl -pe 's/\@section Modifying Strings/\@section 文字列の変更/' -i strings-ja.texi;
	perl -pe 's/\@section Comparison of Characters and Strings/\@section 文字および文字列の比較/' -i strings-ja.texi;
	perl -pe 's/\@section Conversion of Characters and Strings/\@section 文字および文字列の変換/' -i strings-ja.texi;
	perl -pe 's/\@section Formatting Strings/\@section 文字列のフォーマット/' -i strings-ja.texi;
	perl -pe 's/\@section Case Conversion in Lisp/\@section Lispでの大文字小文字変換/' -i strings-ja.texi;
	perl -pe 's/\@section The Case Table/\@section caseテーブル/' -i strings-ja.texi;
	;;
    lists-ja.texi)
	perl -pe 's/\@chapter Lists/\@chapter リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Lists and Cons Cells/\@section リストとコンスセル/' -i lists-ja.texi;
	perl -pe 's/\@section Predicates on Lists/\@section リストのための述語/' -i lists-ja.texi;
	perl -pe 's/\@section Accessing Elements of Lists/\@section リスト要素へのアクセス/' -i lists-ja.texi;
	perl -pe 's/\@section Building Cons Cells and Lists/\@section コンスセルおよびリストの構築/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying List Variables/\@section リスト変数の変更/' -i lists-ja.texi;
	perl -pe 's/\@section Modifying Existing List Structure/\@section 既存のリスト構造の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering List Elements with \@code\{setcar\}/\@subsection \@code\{setcar\}によるリスト要素の変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Altering the CDR of a List/\@subsection リストのCDRの変更/' -i lists-ja.texi;
	perl -pe 's/\@subsection Functions that Rearrange Lists/\@subsection リストを再配置する関数/' -i lists-ja.texi;
	perl -pe 's/\@section Using Lists as Sets/\@section 集合としてのリストの使用/' -i lists-ja.texi;
	perl -pe 's/\@section Association Lists/\@section 連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@section Property Lists/\@section プロパティリスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists and Association Lists/\@subsection プロパティリストと連想リスト/' -i lists-ja.texi;
	perl -pe 's/\@subsection Property Lists Outside Symbols/\@subsection プロパティリストと外部シンボル/' -i lists-ja.texi;
	;;
    sequences-ja.texi)
	perl -pe 's/\@chapter Sequences, Arrays, and Vectors/\@chapter シーケンス、配列、ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Sequences/\@section シーケンス/' -i sequences-ja.texi;
	perl -pe 's/\@section Arrays/\@section 配列/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions that Operate on Arrays/\@section 配列を操作する関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Vectors/\@section ベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Functions for Vectors/\@section ベクターのための関数/' -i sequences-ja.texi;
	perl -pe 's/\@section Char-Tables/\@section 文字テーブル/' -i sequences-ja.texi;
	perl -pe 's/\@section Bool-vectors/\@section ブールベクター/' -i sequences-ja.texi;
	perl -pe 's/\@section Managing a Fixed-Size Ring of Objects/\@section オブジェクト用固定長リングの管理/' -i sequences-ja.texi;
	;;
    hash-ja.texi)
	perl -pe 's/\@chapter Hash Tables/\@chapter ハッシュテーブル/' -i hash-ja.texi;
	perl -pe 's/\@section Creating Hash Tables/\@section ハッシュテーブルの作成/' -i hash-ja.texi;
	perl -pe 's/\@section Hash Table Access/\@section ハッシュテーブルへのアクセス/' -i hash-ja.texi;
	perl -pe 's/\@section Defining Hash Comparisons/\@section ハッシュの比較の定義/' -i hash-ja.texi;
	perl -pe 's/\@section Other Hash Table Functions/\@section ハッシュテーブルのためのその他関数/' -i hash-ja.texi;
	;;
    symbols-ja.texi)
	perl -pe 's/\@chapter Symbols/\@chapter シンボル/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Components/\@section シンボルの構成要素/' -i symbols-ja.texi;
	perl -pe 's/\@section Defining Symbols/\@section シンボルの定義/' -i symbols-ja.texi;
	perl -pe 's/\@section Creating and Interning Symbols/\@section シンボルの作成とintern/' -i symbols-ja.texi;
	perl -pe 's/\@section Symbol Properties/\@section シンボルのプロパティ/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Accessing Symbol Properties/\@subsection シンボルのプロパティへのアクセス/' -i symbols-ja.texi;
	perl -pe 's/\@subsection Standard Symbol Properties/\@subsection シンボルの標準的なプロパティ/' -i symbols-ja.texi;
	;;
    eval-ja.texi)
	perl -pe 's/\@chapter Evaluation/\@chapter 評価/' -i eval-ja.texi;
	perl -pe 's/\@section Introduction to Evaluation/\@section 評価の概要/' -i eval-ja.texi;
	perl -pe 's/\@section Kinds of Forms/\@section フォームの種類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Self-Evaluating Forms/\@subsection 自己評価を行うフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Forms/\@subsection シンボルのフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Classification of List Forms/\@subsection リストフォームの分類/' -i eval-ja.texi;
	perl -pe 's/\@subsection Symbol Function Indirection/\@subsection シンボル関数インダイレクション/' -i eval-ja.texi;
	perl -pe 's/\@subsection Evaluation of Function Forms/\@subsection 関数フォームの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Lisp Macro Evaluation/\@subsection Lispマクロの評価/' -i eval-ja.texi;
	perl -pe 's/\@subsection Special Forms/\@subsection スペシャルフォーム/' -i eval-ja.texi;
	perl -pe 's/\@subsection Autoloading/\@subsection 自動ロード/' -i eval-ja.texi;
	perl -pe 's/\@section Quoting/\@section クォート/' -i eval-ja.texi;
	perl -pe 's/\@section Backquote/\@section バッククォート/' -i eval-ja.texi;
	perl -pe 's/\@section Eval/\@section eval/' -i eval-ja.texi;
	;;
    control-ja.texi)
	perl -pe 's/\@chapter Control Structures/\@chapter 制御構造/' -i control-ja.texi;
	perl -pe 's/\@section Sequencing/\@section 順序/' -i control-ja.texi;
	perl -pe 's/\@section Conditionals/\@section 条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Pattern matching case statement/\@subsection パターンマッチングによるcase文/' -i control-ja.texi;
	perl -pe 's/\@section Constructs for Combining Conditions/\@section 条件の組み合わせ/' -i control-ja.texi;
	perl -pe 's/\@section Iteration/\@section 繰り返し/' -i control-ja.texi;
	perl -pe 's/\@section Nonlocal Exits/\@section 非ローカル脱出/' -i control-ja.texi;
	perl -pe 's/\@subsection Explicit Nonlocal Exits\: \@code\{catch\} and \@code\{throw\}/\@subsection 明示的な非ローカル脱出\: \@code\{catch\}と\@code\{throw\}/' -i control-ja.texi;
	perl -pe 's/\@subsection Examples of \@code\{catch\} and \@code\{throw\}/\@subsection \@code\{catch\}と\@code\{thrown\}の例/' -i control-ja.texi;
	perl -pe 's/\@subsection Errors/\@subsection エラー/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How to Signal an Error/\@subsubsection エラーをシグナルする方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection How Emacs Processes Errors/\@subsubsection Emacsがエラーを処理する方法/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Writing Code to Handle Errors/\@subsubsection エラーを処理するコードの記述/' -i control-ja.texi;
	perl -pe 's/\@subsubsection Error Symbols and Condition Names/\@subsubsection エラーシンボルとエラー条件/' -i control-ja.texi;
	perl -pe 's/\@subsection Cleaning Up from Nonlocal Exits/\@subsection 非ローカル脱出のクリーンアップ/' -i control-ja.texi;
	;;
    variables-ja.texi)
	perl -pe 's/\@chapter Variables/\@chapter 変数/' -i variables-ja.texi;
	perl -pe 's/\@section Global Variables/\@section グローバル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Variables that Never Change/\@section 変更不可な変数/' -i variables-ja.texi;
	perl -pe 's/\@section Local Variables/\@section ローカル変数/' -i variables-ja.texi;
	perl -pe "s/\@section When a Variable is \`\`Void\'\'/\@section 変数が\`\`void\'\'のとき/" -i variables-ja.texi;
	perl -pe 's/\@section Defining Global Variables/\@section グローバル変数の定義/' -i variables-ja.texi;
	perl -pe 's/\@section Tips for Defining Variables Robustly/\@section 堅牢な変数定義のためのヒント/' -i variables-ja.texi;
	perl -pe 's/\@section Accessing Variable Values/\@section 変数の値へのアクセス/' -i variables-ja.texi;
	perl -pe 's/\@section Setting Variable Values/\@section 変数の値のセット/' -i variables-ja.texi;
	perl -pe 's/\@section Scoping Rules for Variable Bindings/\@section 変数のバインディングのスコーピングルール/' -i variables-ja.texi;
	perl -pe 's/\@subsection Dynamic Binding/\@subsection ダイナミックバインディング/' -i variables-ja.texi;
	perl -pe 's/\@subsection Proper Use of Dynamic Binding/\@subsection ダイナミックバインディングの正しい使用/' -i variables-ja.texi;
	perl -pe 's/\@subsection Lexical Binding/\@subsection レキシカルバインディング/' -i variables-ja.texi;
	perl -pe 's/\@subsection Using Lexical Binding/\@subsection レキシカルバインディングの使用/' -i variables-ja.texi;
	perl -pe 's/\@section Buffer-Local Variables/\@section バッファーローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@subsection Introduction to Buffer-Local Variables/\@subsection バッファーローカル変数の概要/' -i variables-ja.texi;
	perl -pe 's/\@subsection Creating and Deleting Buffer-Local Bindings/\@subsection バッファーローカルなバインディングの作成と削除/' -i variables-ja.texi;
	perl -pe 's/\@subsection The Default Value of a Buffer-Local Variable/\@subsection バッファーローカル変数のデフォルト値/' -i variables-ja.texi;
	perl -pe 's/\@section File Local Variables/\@section ファイルローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Directory Local Variables/\@section ディレクトリーローカル変数/' -i variables-ja.texi;
	perl -pe 's/\@section Variable Aliases/\@section 変数のエイリアス/' -i variables-ja.texi;
	perl -pe 's/\@section Variables with Restricted Values/\@section 値を制限された変数/' -i variables-ja.texi;
	perl -pe 's/\@section Generalized Variables/\@section ジェネリック変数/' -i variables-ja.texi;
	perl -pe 's/\@subsection The \@code\{setf\} Macro/\@subsection \@code\{setf\}マクロ/' -i variables-ja.texi;
	perl -pe 's/\@subsection Defining new \@code\{setf\} forms/\@subsection 新たな\@code\{setf\}フォーム/' -i variables-ja.texi;
	;;
    functions-ja.texi)
	perl -pe 's/\@chapter Functions/\@chapter 関数/' -i functions-ja.texi;
	perl -pe 's/\@section What Is a Function\?/\@section 関数とは\?/' -i functions-ja.texi;
	perl -pe 's/\@section Lambda Expressions/\@section ラムダ式/' -i functions-ja.texi;
	perl -pe 's/\@subsection Components of a Lambda Expression/\@subsection ラムダ式の構成要素/' -i functions-ja.texi;
	perl -pe 's/\@subsection A Simple Lambda Expression Example/\@subsection 単純なラムダ式の例/' -i functions-ja.texi;
	perl -pe 's/\@subsection Other Features of Argument Lists/\@subsection 引数リストのその他機能/' -i functions-ja.texi;
	perl -pe 's/\@subsection Documentation Strings of Functions/\@subsection 関数のドキュメント文字列/' -i functions-ja.texi;
	perl -pe 's/\@section Naming a Function/\@section 関数の命名/' -i functions-ja.texi;
	perl -pe 's/\@section Defining Functions/\@section 関数の定義/' -i functions-ja.texi;
	perl -pe 's/\@section Calling Functions/\@section 関数の呼び出し/' -i functions-ja.texi;
	perl -pe 's/\@section Mapping Functions/\@section 関数のマッピング/' -i functions-ja.texi;
	perl -pe 's/\@section Anonymous Functions/\@section 無名関数/' -i functions-ja.texi;
	perl -pe 's/\@section Accessing Function Cell Contents/\@section 関数セルの内容へのアクセス/' -i functions-ja.texi;
	perl -pe 's/\@section Closures/\@section クロージャー/' -i functions-ja.texi;
	perl -pe 's/\@section Advising Emacs Lisp Functions/\@section Emacs Lisp関数にたいするアドバイス/' -i functions-ja.texi;
	perl -pe 's/\@subsection Primitives to manipulate advices/\@subsection アドバイスを操作するためのプリミティブ/' -i functions-ja.texi;
	perl -pe 's/\@subsection Advising Named Functions/\@subsection 名前つき関数にたいするアドバイス/' -i functions-ja.texi;
	perl -pe 's/\@subsection Ways to compose advices/\@subsection アドバイスの構築方法/' -i functions-ja.texi;
	perl -pe 's/\@subsection Adapting code using the old defadvice/\@subsection 古いdefadviceを使用するコードの改良/' -i functions-ja.texi;
	perl -pe 's/\@section Declaring Functions Obsolete/\@section 関数を陳腐と宣言する/' -i functions-ja.texi;
	perl -pe 's/\@section Inline Functions/\@section インライン関数Inline Functions/' -i functions-ja.texi;
	perl -pe 's/\@section The \@code\{declare\} Form/\@section \@code\{declare\}フォーム/' -i functions-ja.texi;
	perl -pe 's/\@section Telling the Compiler that a Function is Defined/\@section コンパイラーへの定義済み関数の指示/' -i functions-ja.texi;
	perl -pe 's/\@section Determining whether a Function is Safe to Call/\@section 安全に関数を呼び出せるかどうかの判断/' -i functions-ja.texi;
	perl -pe 's/\@section Other Topics Related to Functions/\@section 関数に関するその他トピック/' -i functions-ja.texi;
	;;
    macros-ja.texi)
	perl -pe 's/\@chapter Macros/\@chapter マクロ/' -i macros-ja.texi;
	perl -pe 's/\@section A Simple Example of a Macro/\@section 単純なマクロの例/' -i macros-ja.texi;
	perl -pe 's/\@section Expansion of a Macro Call/\@section マクロ呼び出しの展開/' -i macros-ja.texi;
	perl -pe 's/\@section Macros and Byte Compilation/\@section マクロとバイトコンパイル/' -i macros-ja.texi;
	perl -pe 's/\@section Defining Macros/\@section マクロの定義/' -i macros-ja.texi;
	perl -pe 's/\@section Common Problems Using Macros/\@section マクロ使用に関する一般的な問題/' -i macros-ja.texi;
	perl -pe 's/\@subsection Wrong Time/\@subsection タイミング間違い/' -i macros-ja.texi;
	perl -pe 's/\@subsection Evaluating Macro Arguments Repeatedly/\@subsection マクロ引数の多重評価/' -i macros-ja.texi;
	perl -pe 's/\@subsection Local Variables in Macro Expansions/\@subsection マクロ展開でのローカル変数/' -i macros-ja.texi;
	perl -pe 's/\@subsection Evaluating Macro Arguments in Expansion/\@subsection 展開におけるマクロ引数の評価/' -i macros-ja.texi;
	perl -pe 's/\@subsection How Many Times is the Macro Expanded\?/\@subsection マクロが展開される回数は\?/' -i macros-ja.texi;
	perl -pe 's/\@section Indenting Macros/\@section マクロのインデント/' -i macros-ja.texi;
	;;
    customize-ja.texi)
	perl -pe 's/\@chapter Customization Settings/\@chapter カスタマイズ設定/' -i customize-ja.texi;
	perl -pe 's/\@section Common Item Keywords/\@section 一般的なキーワードアイテム/' -i customize-ja.texi;
	perl -pe 's/\@section Defining Customization Groups/\@section カスタマイズグループの定義/' -i customize-ja.texi;
	perl -pe 's/\@section Defining Customization Variables/\@section カスタマイズ変数の定義/' -i customize-ja.texi;
	perl -pe 's/\@section Customization Types/\@section カスタマイズ型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Simple Types/\@subsection 単純型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Composite Types/\@subsection 複合型/' -i customize-ja.texi;
	perl -pe 's/\@subsection Splicing into Lists/\@subsection リストへのスプライス/' -i customize-ja.texi;
	perl -pe 's/\@subsection Type Keywords/\@subsection 型キーワード/' -i customize-ja.texi;
	perl -pe 's/\@subsection Defining New Types/\@subsection 新たな型の定義/' -i customize-ja.texi;
	perl -pe 's/\@section Applying Customizations/\@section カスタマイズの適用/' -i customize-ja.texi;
	perl -pe 's/\@section Custom Themes/\@section カスタムテーマ/' -i customize-ja.texi;
	;;
    loading-ja.texi)
	perl -pe 's/\@chapter Loading/\@chapter ロード/' -i loading-ja.texi;
	perl -pe 's/\@section How Programs Do Loading/\@section プログラムがロードを行う方法/' -i loading-ja.texi;
	perl -pe 's/\@section Load Suffixes/\@section ロードでの拡張子/' -i loading-ja.texi;
	perl -pe 's/\@section Library Search/\@section ライブラリー検索/' -i loading-ja.texi;
	perl -pe 's/\@section Loading Non-\@acronym\{ASCII\} Characters/\@section 非\@acronym\{ASCII\}文字のロード/' -i loading-ja.texi;
	perl -pe 's/\@section Autoload/\@section autoload/' -i loading-ja.texi;
	perl -pe 's/\@section Repeated Loading/\@section 多重ロード/' -i loading-ja.texi;
	perl -pe 's/\@section Features/\@section 名前つき機能/' -i loading-ja.texi;
	perl -pe 's/\@section Which File Defined a Certain Symbol/\@section どのファイルで特定のシンボルが定義されているか/' -i loading-ja.texi;
	perl -pe 's/\@section Unloading/\@section アンロード/' -i loading-ja.texi;
	perl -pe 's/\@section Hooks for Loading/\@section ロードのためのフック/' -i loading-ja.texi;
	;;
    compile-ja.texi)
	perl -pe 's/\@chapter Byte Compilation/\@chapter バイトコンパイル/' -i compile-ja.texi;
	perl -pe 's/\@section Performance of Byte-Compiled Code/\@section バイトコンパイル済みコードのパフォーマンス/' -i compile-ja.texi;
	perl -pe 's/\@section Byte-Compilation Functions/\@section バイトコンパイル関数/' -i compile-ja.texi;
	perl -pe 's/\@section Documentation Strings and Compilation/\@section ドキュメント文字列とコンパイル/' -i compile-ja.texi;
	perl -pe 's/\@section Dynamic Loading of Individual Functions/\@section 個別関数のダイナミックロード/' -i compile-ja.texi;
	perl -pe 's/\@section Evaluation During Compilation/\@section コンパイル中の評価/' -i compile-ja.texi;
	perl -pe 's/\@section Compiler Errors/\@section コンパイラーのエラー/' -i compile-ja.texi;
	perl -pe 's/\@section Byte-Code Function Objects/\@section バイトコード関数オブジェクト/' -i compile-ja.texi;
	perl -pe 's/\@section Disassembled Byte-Code/\@section 逆アセンブルされたバイトコード/' -i compile-ja.texi;
	;;
    debugging-ja.texi)
	perl -pe 's/\@chapter Debugging Lisp Programs/\@chapter Lispプログラムのデバッグ/' -i debugging-ja.texi;
	perl -pe 's/\@section The Lisp Debugger/\@section Lispデバッガ/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Entering the Debugger on an Error/\@subsection エラーによるデバッガへのエンター/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Debugging Infinite Loops/\@subsection 無限ループのデバッグ/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Entering the Debugger on a Function Call/\@subsection 関数呼び出しによるデバッガへのエンター/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Explicit Entry to the Debugger/\@subsection 明示的なデバッガへのエントリー/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Using the Debugger/\@subsection デバッガの使用/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Debugger Commands/\@subsection デバッガのコマンド/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Invoking the Debugger/\@subsection デバッガの呼び出し/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Internals of the Debugger/\@subsection デバッガの内部/' -i debugging-ja.texi;
	perl -pe 's/\@section Debugging Invalid Lisp Syntax/\@section 無効なLisp構文のデバッグ/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Excess Open Parentheses/\@subsection 過剰な開カッコ/' -i debugging-ja.texi;
	perl -pe 's/\@subsection Excess Close Parentheses/\@subsection 過剰な閉カッコ/' -i debugging-ja.texi;
	perl -pe 's/\@section Test Coverage/\@section カバレッジテスト/' -i debugging-ja.texi;
	perl -pe 's/\@section Profiling/\@section プロファイリング/' -i debugging-ja.texi;
	;;
    edebug-ja.texi)
	perl -pe 's/\@section Edebug/\@section Edebug/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Using Edebug/\@subsection Edebugの使用/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Instrumenting for Edebug/\@subsection Edebugのためのインストルメント/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Edebug Execution Modes/\@subsection Edebugの実行モード/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Jumping/\@subsection ジャンプ/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Miscellaneous Edebug Commands/\@subsection その他のEdebugコマンド/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Breaks/\@subsection ブレーク/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Edebug Breakpoints/\@subsubsection Edebugのブレークポイント/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Global Break Condition/\@subsubsection グローバルなブレーク条件/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Source Breakpoints/\@subsubsection ソースブレークポイント/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Trapping Errors/\@subsection エラーのトラップ/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Edebug Views/\@subsection Edebugのビュー/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Evaluation/\@subsection 評価/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Evaluation List Buffer/\@subsection 評価リストバッファー/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Printing in Edebug/\@subsection Edebugでのプリント/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Trace Buffer/\@subsection トレースバッファー/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Coverage Testing/\@subsection カバレッジテスト/' -i edebug-ja.texi;
	perl -pe 's/\@subsection The Outside Context/\@subsection コンテキスト外部/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Checking Whether to Stop/\@subsubsection 停止するかどうかのチェック/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Edebug Display Update/\@subsubsection Edebugの表示の更新/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Edebug Recursive Edit/\@subsubsection Edebugの再帰編集/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Edebug and Macros/\@subsection Edebugとマクロ/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Instrumenting Macro Calls/\@subsubsection マクロ呼び出しのインストルメント/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Specification List/\@subsubsection 仕様リスト/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Backtracking in Specifications/\@subsubsection 仕様でのバックトレース/' -i edebug-ja.texi;
	perl -pe 's/\@subsubsection Specification Examples/\@subsubsection 仕様の例/' -i edebug-ja.texi;
	perl -pe 's/\@subsection Edebug Options/\@subsection Edebugのオプション/' -i edebug-ja.texi;
	;;
    streams-ja.texi)
	perl -pe 's/\@chapter Reading and Printing Lisp Objects/\@chapter Lispオブジェクトの読み取りとプリント/' -i streams-ja.texi;
	perl -pe 's/\@section Introduction to Reading and Printing/\@section 読み取りとプリントの概念/' -i streams-ja.texi;
	perl -pe 's/\@section Input Streams/\@section 入力ストリーム/' -i streams-ja.texi;
	perl -pe 's/\@section Input Functions/\@section 入力関数/' -i streams-ja.texi;
	perl -pe 's/\@section Output Streams/\@section 出力ストリーム/' -i streams-ja.texi;
	perl -pe 's/\@section Output Functions/\@section 出力関数/' -i streams-ja.texi;
	perl -pe 's/\@section Variables Affecting Output/\@section 出力に影響する変数/' -i streams-ja.texi;
	;;
    minibuf-ja.texi)
	perl -pe 's/\@chapter Minibuffers/\@chapter ミニバッファー/' -i minibuf-ja.texi;
	perl -pe 's/\@section Introduction to Minibuffers/\@section ミニバッファーの概念/' -i minibuf-ja.texi;
	perl -pe 's/\@section Reading Text Strings with the Minibuffer/\@section ミニバッファーでのテキスト文字列の読み取り/' -i minibuf-ja.texi;
	perl -pe 's/\@section Reading Lisp Objects with the Minibuffer/\@section ミニバッファーでのLispオブジェクトの読み取り/' -i minibuf-ja.texi;
	perl -pe 's/\@section Minibuffer History/\@section ミニバッファーのヒストリー/' -i minibuf-ja.texi;
	perl -pe 's/\@section Initial Input/\@section 入力の初期値/' -i minibuf-ja.texi;
	perl -pe 's/\@section Completion/\@section 補完/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Basic Completion Functions/\@subsection 基本的な補完関数/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Completion and the Minibuffer/\@subsection 補完とミニバッファー/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Minibuffer Commands that Do Completion/\@subsection 補完を行うミニバッファーコマンド/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection High-Level Completion Functions/\@subsection 高レベルの補完関数/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Reading File Names/\@subsection ファイル名の読み取り/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Completion Variables/\@subsection 補完変数/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Programmed Completion/\@subsection プログラムされた補完/' -i minibuf-ja.texi;
	perl -pe 's/\@subsection Completion in Ordinary Buffers/\@subsection 通常バッファーでの補完/' -i minibuf-ja.texi;
	perl -pe 's/\@section Yes-or-No Queries/\@section Yes-or-Noによる問い合わせ/' -i minibuf-ja.texi;
	perl -pe 's/\@section Asking Multiple Y-or-N Questions/\@section 複数のY-or-Nの問い合わせ/' -i minibuf-ja.texi;
	perl -pe 's/\@section Reading a Password/\@section パスワードの読み取り/' -i minibuf-ja.texi;
	perl -pe 's/\@section Minibuffer Commands/\@section ミニバッファーのコマンド/' -i minibuf-ja.texi;
	perl -pe 's/\@section Minibuffer Windows/\@section ミニバッファーのウィンドウ/' -i minibuf-ja.texi;
	perl -pe 's/\@section Minibuffer Contents/\@section ミニバッファーのコンテンツ/' -i minibuf-ja.texi;
	perl -pe 's/\@section Recursive Minibuffers/\@section 再帰的なミニバッファー/' -i minibuf-ja.texi;
	perl -pe 's/\@section Minibuffer Miscellany/\@section ミニバッファー、その他の事項/' -i minibuf-ja.texi;
	;;
    commands-ja.texi)
	perl -pe 's/\@chapter Command Loop/\@chapter コマンドループ/' -i commands-ja.texi;
	perl -pe 's/\@section Command Loop Overview/\@section コマンドループの概要/' -i commands-ja.texi;
	perl -pe 's/\@section Defining Commands/\@section コマンドの定義/' -i commands-ja.texi;
	perl -pe 's/\@subsection Using \@code\{interactive\}/\@subsection \@code\{interactive\}の使用/' -i commands-ja.texi;
	perl -pe 's/\@subsection Code Characters for \@code\{interactive\}/\@subsection \@code\{interactive\}にたいするコード文字/' -i commands-ja.texi;
	perl -pe 's/\@subsection Examples of Using \@code\{interactive\}/\@subsection \@code\{interactive\}の使用例/' -i commands-ja.texi;
	perl -pe 's/\@subsection Select among Command Alternatives/\@subsection コマンド候補からの選択/' -i commands-ja.texi;
	perl -pe 's/\@section Interactive Call/\@section interactiveな呼び出し/' -i commands-ja.texi;
	perl -pe 's/\@section Distinguish Interactive Calls/\@section interactiveな呼び出しの区別/' -i commands-ja.texi;
	perl -pe 's/\@section Information from the Command Loop/\@section コマンドループからの情報/' -i commands-ja.texi;
	perl -pe 's/\@section Adjusting Point After Commands/\@section コマンド後のポイントの調整/' -i commands-ja.texi;
	perl -pe 's/\@section Input Events/\@section 入力イベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Keyboard Events/\@subsection キーボードイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Function Keys/\@subsection ファンクションキー/' -i commands-ja.texi;
	perl -pe 's/\@subsection Mouse Events/\@subsection マウスイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Click Events/\@subsection クリックイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Drag Events/\@subsection ドラッグイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Button-Down Events/\@subsection ボタンダウンイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Repeat Events/\@subsection リピートイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Motion Events/\@subsection モーションイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Focus Events/\@subsection フォーカスイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Miscellaneous System Events/\@subsection その他のシステムイベント/' -i commands-ja.texi;
	perl -pe 's/\@subsection Event Examples/\@subsection イベントの例/' -i commands-ja.texi;
	perl -pe 's/\@subsection Classifying Events/\@subsection イベントの分類/' -i commands-ja.texi;
	perl -pe 's/\@subsection Accessing Mouse Events/\@subsection マウスイベントへのアクセス/' -i commands-ja.texi;
	perl -pe 's/\@subsection Accessing Scroll Bar Events/\@subsection スクロールバーイベントへのアクセス/' -i commands-ja.texi;
	perl -pe 's/\@subsection Putting Keyboard Events in Strings/\@subsection 文字列内へのキーボードイベントの配置/' -i commands-ja.texi;
	perl -pe 's/\@section Reading Input/\@section 入力の読み取り/' -i commands-ja.texi;
	perl -pe 's/\@subsection Key Sequence Input/\@subsection キーシーケンス入力/' -i commands-ja.texi;
	perl -pe 's/\@subsection Reading One Event/\@subsection 単一イベントの読み取り/' -i commands-ja.texi;
	perl -pe 's/\@subsection Modifying and Translating Input Events/\@subsection 入力イベントの変更と変換/' -i commands-ja.texi;
	perl -pe 's/\@subsection Invoking the Input Method/\@subsection 入力メソッドの呼び出し/' -i commands-ja.texi;
	perl -pe 's/\@subsection Quoted Character Input/\@subsection クォートされた文字の入力/' -i commands-ja.texi;
	perl -pe 's/\@subsection Miscellaneous Event Input Features/\@subsection その他のイベント入力の機能/' -i commands-ja.texi;
	perl -pe 's/\@section Special Events/\@section スペシャルイベント/' -i commands-ja.texi;
	perl -pe 's/\@section Waiting for Elapsed Time or Input/\@section 時間の経過や入力の待機/' -i commands-ja.texi;
	perl -pe 's/\@section Quitting/\@section quit/' -i commands-ja.texi;
	perl -pe 's/\@section Prefix Command Arguments/\@section プレフィクスコマンド引数/' -i commands-ja.texi;
	perl -pe 's/\@section Recursive Editing/\@section 再帰編集/' -i commands-ja.texi;
	perl -pe 's/\@section Disabling Commands/\@section コマンドの無効化/' -i commands-ja.texi;
	perl -pe 's/\@section Command History/\@section コマンドのヒストリー/' -i commands-ja.texi;
	perl -pe 's/\@section Keyboard Macros/\@section キーボードマクロ/' -i commands-ja.texi;
	;;
    keymaps-ja.texi)
	perl -pe 's/\@chapter Keymaps/\@chapter キーマップ/' -i keymaps-ja.texi;
	perl -pe 's/\@section Key Sequences/\@section キーシーケンス/' -i keymaps-ja.texi;
	perl -pe 's/\@section Keymap Basics/\@section キーマップの基礎/' -i keymaps-ja.texi;
	perl -pe 's/\@section Format of Keymaps/\@section キーマップのフォーマット/' -i keymaps-ja.texi;
	perl -pe 's/\@section Creating Keymaps/\@section キーマップの作成/' -i keymaps-ja.texi;
	perl -pe 's/\@section Inheritance and Keymaps/\@section 継承とキーマップ/' -i keymaps-ja.texi;
	perl -pe 's/\@section Prefix Keys/\@section プレフィクスキー/' -i keymaps-ja.texi;
	perl -pe 's/\@section Active Keymaps/\@section アクティブなキーマップ/' -i keymaps-ja.texi;
	perl -pe 's/\@section Searching the Active Keymaps/\@section アクティブなキーマップの検索/' -i keymaps-ja.texi;
	perl -pe 's/\@section Controlling the Active Keymaps/\@section アクティブなキーマップの制御/' -i keymaps-ja.texi;
	perl -pe 's/\@section Key Lookup/\@section キーの照合/' -i keymaps-ja.texi;
	perl -pe 's/\@section Functions for Key Lookup/\@section キー照合のための関数/' -i keymaps-ja.texi;
	perl -pe 's/\@section Changing Key Bindings/\@section キーバインディングの変更/' -i keymaps-ja.texi;
	perl -pe 's/\@section Remapping Commands/\@section コマンドのリマップ/' -i keymaps-ja.texi;
	perl -pe 's/\@section Keymaps for Translating Sequences of Events/\@section イベントシーケンス変換のためのキーマップ/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Interaction with normal keymaps/\@subsection 通常のキーマップとの対話/' -i keymaps-ja.texi;
	perl -pe 's/\@section Commands for Binding Keys/\@section キーのバインドのためのコマンド/' -i keymaps-ja.texi;
	perl -pe 's/\@section Scanning Keymaps/\@section キーマップのスキャン/' -i keymaps-ja.texi;
	perl -pe 's/\@section Menu Keymaps/\@section メニューキーアップ/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Defining Menus/\@subsection メニューの定義/' -i keymaps-ja.texi;
	perl -pe 's/\@subsubsection Simple Menu Items/\@subsubsection 単純なメニューアイテム/' -i keymaps-ja.texi;
	perl -pe 's/\@subsubsection Extended Menu Items/\@subsubsection 拡張メニューアイテム/' -i keymaps-ja.texi;
	perl -pe 's/\@subsubsection Menu Separators/\@subsubsection メニューセパレーター/' -i keymaps-ja.texi;
	perl -pe 's/\@subsubsection Alias Menu Items/\@subsubsection メニューアイテムのエイリアス/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Menus and the Mouse/\@subsection メニューとマウス/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Menus and the Keyboard/\@subsection メニューとキーボード/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Menu Example/\@subsection メニューの例/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection The Menu Bar/\@subsection メニューバー Bar/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Tool bars/\@subsection ツールバー/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Modifying Menus/\@subsection メニューの変更/' -i keymaps-ja.texi;
	perl -pe 's/\@subsection Easy Menu/\@subsection easy-menu/' -i keymaps-ja.texi;
	;;
    modes-ja.texi)
	perl -pe 's/\@chapter Major and Minor Modes/\@chapter メジャーモードとマイナーモード/' -i modes-ja.texi;
	perl -pe 's/\@section Hooks/\@section フック/' -i modes-ja.texi;
	perl -pe 's/\@subsection Running Hooks/\@subsection フックの実行/' -i modes-ja.texi;
	perl -pe 's/\@subsection Setting Hooks/\@subsection フックのセットSetting Hooks/' -i modes-ja.texi;
	perl -pe 's/\@section Major Modes/\@section メジャーモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Major Mode Conventions/\@subsection メジャーモードの慣習/' -i modes-ja.texi;
	perl -pe 's/\@subsection How Emacs Chooses a Major Mode/\@subsection Emacsがメジャーモードを選択する方法/' -i modes-ja.texi;
	perl -pe 's/\@subsection Getting Help about a Major Mode/\@subsection メジャーモードでのヘルプ入手/' -i modes-ja.texi;
	perl -pe 's/\@subsection Defining Derived Modes/\@subsection 派生モードの定義/' -i modes-ja.texi;
	perl -pe 's/\@subsection Basic Major Modes/\@subsection 基本的なメジャーモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Mode Hooks/\@subsection モードフック/' -i modes-ja.texi;
	perl -pe 's/\@subsection Tabulated List mode/\@subsection Tabulated Listモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Generic Modes/\@subsection ジェネリックモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Major Mode Examples/\@subsection メジャーモードの例/' -i modes-ja.texi;
	perl -pe 's/\@section Minor Modes/\@section マイナーモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Conventions for Writing Minor Modes/\@subsection マイナーモード記述の規約/' -i modes-ja.texi;
	perl -pe 's/\@subsection Keymaps and Minor Modes/\@subsection キーマップとマイナーモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Defining Minor Modes/\@subsection マイナーモードの定義/' -i modes-ja.texi;
	perl -pe 's/\@section Mode Line Format/\@section モードラインのフォーマット/' -i modes-ja.texi;
	perl -pe 's/\@subsection Mode Line Basics/\@subsection モードラインの基礎/' -i modes-ja.texi;
	perl -pe 's/\@subsection The Data Structure of the Mode Line/\@subsection モードラインのデータ構造/' -i modes-ja.texi;
	perl -pe 's/\@subsection The Top Level of Mode Line Control/\@subsection モードライン制御のトップレベル/' -i modes-ja.texi;
	perl -pe 's/\@subsection Variables Used in the Mode Line/\@subsection モードラインで使用される変数/' -i modes-ja.texi;
	perl -pe 's/\@subsection \@code\{%\}-Constructs in the Mode Line/\@subsection モードラインでの\@code\{%\}構造/' -i modes-ja.texi;
	perl -pe 's/\@subsection Properties in the Mode Line/\@subsection モードラインでのプロパティ/' -i modes-ja.texi;
	perl -pe 's/\@subsection Window Header Lines/\@subsection ウィンドウのヘッダーライン/' -i modes-ja.texi;
	perl -pe 's/\@subsection Emulating Mode Line Formatting/\@subsection モードラインのフォーマットのエミュレート/' -i modes-ja.texi;
	perl -pe 's/\@section Imenu/\@section Imenu/' -i modes-ja.texi;
	perl -pe 's/\@section Font Lock Mode/\@section Font Lockモード/' -i modes-ja.texi;
	perl -pe 's/\@subsection Font Lock Basics/\@subsection Font Lockの基礎/' -i modes-ja.texi;
	perl -pe 's/\@subsection Search-based Fontification/\@subsection 検索ベースのフォント化/' -i modes-ja.texi;
	perl -pe 's/\@subsection Customizing Search-Based Fontification/\@subsection 検索ベースのフォント化のカスタマイズ/' -i modes-ja.texi;
	perl -pe 's/\@subsection Other Font Lock Variables/\@subsection Font Lockのその他の変数/' -i modes-ja.texi;
	perl -pe 's/\@subsection Levels of Font Lock/\@subsection Font Lockのレベル/' -i modes-ja.texi;
	perl -pe 's/\@subsection Precalculated Fontification/\@subsection 事前計算されたフォント化/' -i modes-ja.texi;
	perl -pe 's/\@subsection Faces for Font Lock/\@subsection Font Lockのためのフェイス/' -i modes-ja.texi;
	perl -pe 's/\@subsection Syntactic Font Lock/\@subsection 構文的なFont Lock/' -i modes-ja.texi;
	perl -pe 's/\@subsection Multiline Font Lock Constructs/\@subsection 複数行のFont Lock構造/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Font Lock Multiline/\@subsubsection 複数行のFont Lock/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Region to Fontify after a Buffer Change/\@subsubsection バッファー変更後のリージョンのフォント化/' -i modes-ja.texi;
	perl -pe 's/\@section Automatic Indentation of code/\@section コードの自動インデント/' -i modes-ja.texi;
	perl -pe 's/\@subsection Simple Minded Indentation Engine/\@subsection SMIE\: 無邪気なインデントエンジン/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection SMIE Setup and Features/\@subsubsection SMIEのセットアップと機能/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Operator Precedence Grammars/\@subsubsection 演算子順位文法/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Defining the Grammar of a Language/\@subsubsection 言語の文法の定義/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Defining Tokens/\@subsubsection トークンの定義/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Living With a Weak Parser/\@subsubsection 非力なパーサーの使用/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Specifying Indentation Rules/\@subsubsection インデントルールの指定/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Helper Functions for Indentation Rules/\@subsubsection インデントルールにたいするヘルパー関数/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Sample Indentation Rules/\@subsubsection インデントルールの例/' -i modes-ja.texi;
	perl -pe 's/\@subsubsection Customizing Indentation/\@subsubsection インデントのカスタマイズ/' -i modes-ja.texi;
	perl -pe 's/\@section Desktop Save Mode/\@section Desktop Saveモード/' -i modes-ja.texi;
	;;
    help-ja.texi)
	perl -pe 's/\@chapter Documentation/\@chapter ドキュメント/' -i help-ja.texi;
	perl -pe 's/\@section Documentation Basics/\@section ドキュメントの基礎/' -i help-ja.texi;
	perl -pe 's/\@section Access to Documentation Strings/\@section ドキュメント文字列へのアクセス/' -i help-ja.texi;
	perl -pe 's/\@section Substituting Key Bindings in Documentation/\@section ドキュメント内でのキーバインディングの置き換え/' -i help-ja.texi;
	perl -pe 's/\@section Describing Characters for Help Messages/\@section ヘルプメッセージの文字記述/' -i help-ja.texi;
	perl -pe 's/\@section Help Functions/\@section ヘルプ関数/' -i help-ja.texi;
	;;
    files-ja.texi)
	perl -pe 's/\@chapter Files/\@chapter ファイル/' -i files-ja.texi;
	perl -pe 's/\@section Visiting Files/\@section ファイルのvisit/' -i files-ja.texi;
	perl -pe 's/\@subsection Functions for Visiting Files/\@subsection ファイルをvisitする関数/' -i files-ja.texi;
	perl -pe 's/\@subsection Subroutines of Visiting/\@subsection visitのためのサブルーチン/' -i files-ja.texi;
	perl -pe 's/\@section Saving Buffers/\@section バッファーの保存/' -i files-ja.texi;
	perl -pe 's/\@section Reading from Files/\@section ファイルの読み込み/' -i files-ja.texi;
	perl -pe 's/\@section Writing to Files/\@section ファイルの書き込み/' -i files-ja.texi;
	perl -pe 's/\@section File Locks/\@section ファイルのロック/' -i files-ja.texi;
	perl -pe 's/\@section Information about Files/\@section ファイルの情報/' -i files-ja.texi;
	perl -pe 's/\@subsection Testing Accessibility/\@subsection アクセシビリティのテスト/' -i files-ja.texi;
	perl -pe 's/\@subsection Distinguishing Kinds of Files/\@subsection ファイル種別の区別/' -i files-ja.texi;
	perl -pe 's/\@subsection Truenames/\@subsection 本当の名前/' -i files-ja.texi;
	perl -pe 's/\@subsection File Attributes/\@subsection ファイルの属性/' -i files-ja.texi;
	perl -pe 's/\@subsection Extended File Attributes/\@subsection 拡張されたファイル属性/' -i files-ja.texi;
	perl -pe 's/\@subsection Locating Files in Standard Places/\@subsection 標準的な場所へのファイルの配置/' -i files-ja.texi;
	perl -pe 's/\@section Changing File Names and Attributes/\@section ファイルの名前と属性の変更/' -i files-ja.texi;
	perl -pe 's/\@section File Names/\@section ファイルの名前/' -i files-ja.texi;
	perl -pe 's/\@subsection File Name Components/\@subsection ファイル名の構成要素/' -i files-ja.texi;
	perl -pe 's/\@subsection Absolute and Relative File Names/\@subsection 絶対ファイル名と相対ファイル名/' -i files-ja.texi;
	perl -pe 's/\@subsection Directory Names/\@subsection ディレクトリーの名前/' -i files-ja.texi;
	perl -pe 's/\@subsection Functions that Expand Filenames/\@subsection ファイル名を展開する関数/' -i files-ja.texi;
	perl -pe 's/\@subsection Generating Unique File Names/\@subsection 一意なファイル名の生成/' -i files-ja.texi;
	perl -pe 's/\@subsection File Name Completion/\@subsection ファイル名の補完/' -i files-ja.texi;
	perl -pe 's/\@subsection Standard File Names/\@subsection 標準的なファイル名/' -i files-ja.texi;
	perl -pe 's/\@section Contents of Directories/\@section ディレクトリーのコンテンツ/' -i files-ja.texi;
	perl -pe 's/\@section Creating, Copying and Deleting Directories/\@section ディレクトリーの作成・コピー・削除/' -i files-ja.texi;
	perl -pe "s/\@section Making Certain File Names \`\`Magic\'\'/\@section 特定のファイル名の\`\`Magic\'\'の作成/" -i files-ja.texi;
	perl -pe 's/\@section File Format Conversion/\@section ファイルのフォーマット変換/' -i files-ja.texi;
	perl -pe 's/\@subsection Overview/\@subsection 概要/' -i files-ja.texi;
	perl -pe 's/\@subsection Round-Trip Specification/\@subsection ラウンドトリップ仕様/' -i files-ja.texi;
	perl -pe 's/\@subsection Piecemeal Specification/\@subsection 漸次仕様/' -i files-ja.texi;
	;;
    backups-ja.texi)
	perl -pe 's/\@chapter Backups and Auto-Saving/\@chapter バックアップと自動保存/' -i backups-ja.texi;
	perl -pe 's/\@section Backup Files/\@section ファイルのバックアップ/' -i backups-ja.texi;
	perl -pe 's/\@subsection Making Backup Files/\@subsection バックアップファイルの作成/' -i backups-ja.texi;
	perl -pe 's/\@subsection Backup by Renaming or by Copying\?/\@subsection リネームかコピーのどちらでバックアップするか\?/' -i backups-ja.texi;
	perl -pe 's/\@subsection Making and Deleting Numbered Backup Files/\@subsection 番号つきバックアップファイルの作成と削除/' -i backups-ja.texi;
	perl -pe 's/\@subsection Naming Backup Files/\@subsection バックアップファイルの命名/' -i backups-ja.texi;
	perl -pe 's/\@section Auto-Saving/\@section 自動保存/' -i backups-ja.texi;
	perl -pe 's/\@section Reverting/\@section リバート/' -i backups-ja.texi;
	;;
    buffers-ja.texi)
	perl -pe 's/\@chapter Buffers/\@chapter バッファー/' -i buffers-ja.texi;
	perl -pe 's/\@section Buffer Basics/\@section バッファーの基礎/' -i buffers-ja.texi;
	perl -pe 's/\@section The Current Buffer/\@section カレントバッファー/' -i buffers-ja.texi;
	perl -pe 's/\@section Buffer Names/\@section バッファーの名前/' -i buffers-ja.texi;
	perl -pe 's/\@section Buffer File Name/\@section バッファーのファイル名/' -i buffers-ja.texi;
	perl -pe 's/\@section Buffer Modification/\@section バッファーの変更/' -i buffers-ja.texi;
	perl -pe 's/\@section Buffer Modification Time/\@section バッファーの変更時刻/' -i buffers-ja.texi;
	perl -pe 's/\@section Read-Only Buffers/\@section 読み取り専用のバッファー/' -i buffers-ja.texi;
	perl -pe 's/\@section The Buffer List/\@section バッファーリスト/' -i buffers-ja.texi;
	perl -pe 's/\@section Creating Buffers/\@section バッファーの作成/' -i buffers-ja.texi;
	perl -pe 's/\@section Killing Buffers/\@section バッファーのkill/' -i buffers-ja.texi;
	perl -pe 's/\@section Indirect Buffers/\@section インダイレクトバッファー/' -i buffers-ja.texi;
	perl -pe 's/\@section Swapping Text Between Two Buffers/\@section 2つのバッファー間でのテキストの交換/' -i buffers-ja.texi;
	perl -pe 's/\@section The Buffer Gap/\@section バッファーのギャップ/' -i buffers-ja.texi;
	;;
    windows-ja.texi)
	perl -pe 's/\@chapter Windows/\@chapter ウィンドウ/' -i windows-ja.texi;
	perl -pe 's/\@section Basic Concepts of Emacs Windows/\@section Emacsウィンドウの基本概念/' -i windows-ja.texi;
	perl -pe 's/\@section Windows and Frames/\@section ウィンドウとフレーム/' -i windows-ja.texi;
	perl -pe 's/\@section Window Sizes/\@section ウィンドウのサイズ/' -i windows-ja.texi;
	perl -pe 's/\@section Resizing Windows/\@section ウィンドウのリサイズ/' -i windows-ja.texi;
	perl -pe 's/\@section Splitting Windows/\@section ウィンドウの分割/' -i windows-ja.texi;
	perl -pe 's/\@section Deleting Windows/\@section ウィンドウの削除/' -i windows-ja.texi;
	perl -pe 's/\@section Recombining Windows/\@section ウィンドウの再結合/' -i windows-ja.texi;
	perl -pe 's/\@section Selecting Windows/\@section ウィンドウの選択/' -i windows-ja.texi;
	perl -pe 's/\@section Cyclic Ordering of Windows/\@section ウィンドウのサイクル順/' -i windows-ja.texi;
	perl -pe 's/\@section Buffers and Windows/\@section バッファーとウィンドウ/' -i windows-ja.texi;
	perl -pe 's/\@section Switching to a Buffer in a Window/\@section ウィンドウ内のバッファーへの切り替え/' -i windows-ja.texi;
	perl -pe 's/\@section Choosing a Window for Display/\@section 表示するウィンドウの選択/' -i windows-ja.texi;
	perl -pe 's/\@section Action Functions for \@code\{display-buffer\}/\@section \@code\{display-buffer\}にたいするアクション関数/' -i windows-ja.texi;
	perl -pe 's/\@section Additional Options for Displaying Buffers/\@section バッファー表示の追加オプション/' -i windows-ja.texi;
	perl -pe 's/\@section Window History/\@section ウィンドウのヒストリー/' -i windows-ja.texi;
	perl -pe 's/\@section Dedicated Windows/\@section 専用のウィンドウ/' -i windows-ja.texi;
	perl -pe 's/\@section Quitting Windows/\@section ウィンドウのquit/' -i windows-ja.texi;
	perl -pe 's/\@section Windows and Point/\@section ウィンドウとポイント/' -i windows-ja.texi;
	perl -pe 's/\@section The Window Start and End Positions/\@section ウィンドウの開始位置と終了位置/' -i windows-ja.texi;
	perl -pe 's/\@section Textual Scrolling/\@section テキスト的なスクロール/' -i windows-ja.texi;
	perl -pe 's/\@section Vertical Fractional Scrolling/\@section 割り合いによる垂直スクロール/' -i windows-ja.texi;
	perl -pe 's/\@section Horizontal Scrolling/\@section 水平スクロール/' -i windows-ja.texi;
	perl -pe 's/\@section Coordinates and Windows/\@section 座標とウィンドウ/' -i windows-ja.texi;
	perl -pe 's/\@section Window Configurations/\@section ウィンドウの構成/' -i windows-ja.texi;
	perl -pe 's/\@section Window Parameters/\@section ウィンドウのパラメーター/' -i windows-ja.texi;
	perl -pe 's/\@section Hooks for Window Scrolling and Changes/\@section ウィンドウのスクロールと変更のためのフック/' -i windows-ja.texi;
	;;
    frames-ja.texi)
	perl -pe 's/\@chapter Frames/\@chapter フレーム/' -i frames-ja.texi;
	perl -pe 's/\@section Creating Frames/\@section フレームの作成/' -i frames-ja.texi;
	perl -pe 's/\@section Multiple Terminals/\@section 複数の端末/' -i frames-ja.texi;
	perl -pe 's/\@section Frame Parameters/\@section フレームのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsection Access to Frame Parameters/\@subsection フレームパラメーターへのアクセス/' -i frames-ja.texi;
	perl -pe 's/\@subsection Initial Frame Parameters/\@subsection フレームの初期パラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsection Window Frame Parameters/\@subsection ウィンドウフレームパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Basic Parameters/\@subsubsection 基本パラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Position Parameters/\@subsubsection 位置のパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Size Parameters/\@subsubsection サイズのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Layout Parameters/\@subsubsection レイアウトのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Buffer Parameters/\@subsubsection バッファーのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Window Management Parameters/\@subsubsection ウィンドウ管理のパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Cursor Parameters/\@subsubsection カーソルのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsubsection Font and Color Parameters/\@subsubsection フォントとカラーのパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@subsection Frame Size And Position/\@subsection フレームのサイズと位置/' -i frames-ja.texi;
	perl -pe 's/\@subsection Geometry/\@subsection ジオメトリー/' -i frames-ja.texi;
	perl -pe 's/\@section Terminal Parameters/\@section 端末のパラメーター/' -i frames-ja.texi;
	perl -pe 's/\@section Frame Titles/\@section フレームのタイトル/' -i frames-ja.texi;
	perl -pe 's/\@section Deleting Frames/\@section フレームの削除/' -i frames-ja.texi;
	perl -pe 's/\@section Finding All Frames/\@section すべてのフレームを探す/' -i frames-ja.texi;
	perl -pe 's/\@section Minibuffers and Frames/\@section ミニバッファーとフレーム/' -i frames-ja.texi;
	perl -pe 's/\@section Input Focus/\@section 入力のフォーカス/' -i frames-ja.texi;
	perl -pe 's/\@section Visibility of Frames/\@section フレームの可視性/' -i frames-ja.texi;
	perl -pe 's/\@section Raising and Lowering Frames/\@section フレームを前面や背面に移動する/' -i frames-ja.texi;
	perl -pe 's/\@section Frame Configurations/\@section フレーム構成/' -i frames-ja.texi;
	perl -pe 's/\@section Mouse Tracking/\@section マウスの追跡/' -i frames-ja.texi;
	perl -pe 's/\@section Mouse Position/\@section マウスの位置/' -i frames-ja.texi;
	perl -pe 's/\@section Pop-Up Menus/\@section ポップアップメニュー/' -i frames-ja.texi;
	perl -pe 's/\@section Dialog Boxes/\@section ダイアログボックス/' -i frames-ja.texi;
	perl -pe 's/\@section Pointer Shape/\@section ポインターの形状/' -i frames-ja.texi;
	perl -pe 's/\@section Window System Selections/\@section ウィンドウシステムによる選択/' -i frames-ja.texi;
	perl -pe 's/\@section Drag and Drop/\@section ドラッグアンドドロップ/' -i frames-ja.texi;
	perl -pe 's/\@section Color Names/\@section カラー名/' -i frames-ja.texi;
	perl -pe 's/\@section Text Terminal Colors/\@section テキスト端末のカラー/' -i frames-ja.texi;
	perl -pe 's/\@section X Resources/\@section Xリソース/' -i frames-ja.texi;
	perl -pe 's/\@section Display Feature Testing/\@section ディスプレー機能のテスト/' -i frames-ja.texi;
	;;
    positions-ja.texi)
	perl -pe 's/\@chapter Positions/\@chapter ポジション/' -i positions-ja.texi;
	perl -pe 's/\@section Point/\@section ポイント/' -i positions-ja.texi;
	perl -pe 's/\@section Motion/\@section モーション/' -i positions-ja.texi;
	perl -pe 's/\@subsection Motion by Characters/\@subsection 文字単位の移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Motion by Words/\@subsection 単語単位の移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Motion to an End of the Buffer/\@subsection バッファー終端への移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Motion by Text Lines/\@subsection テキスト行単位の移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Motion by Screen Lines/\@subsection スクリーン行単位の移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Moving over Balanced Expressions/\@subsection バランスのとれたカッコを越えた移動/' -i positions-ja.texi;
	perl -pe 's/\@subsection Skipping Characters/\@subsection 文字のスキップ/' -i positions-ja.texi;
	perl -pe 's/\@section Excursions/\@section エクスカーション/' -i positions-ja.texi;
	perl -pe 's/\@section Narrowing/\@section ナローイング/' -i positions-ja.texi;
	;;
    markers-ja.texi)
	perl -pe 's/\@chapter Markers/\@chapter マーカー/' -i markers-ja.texi;
	perl -pe 's/\@section Overview of Markers/\@section マーカーの概要/' -i markers-ja.texi;
	perl -pe 's/\@section Predicates on Markers/\@section マーカーのための述語/' -i markers-ja.texi;
	perl -pe 's/\@section Functions that Create Markers/\@section マーカーを作成する関数/' -i markers-ja.texi;
	perl -pe 's/\@section Information from Markers/\@section マーカーからの情報/' -i markers-ja.texi;
	perl -pe 's/\@section Marker Insertion Types/\@section Marker 挿入タイプ/' -i markers-ja.texi;
	perl -pe 's/\@section Moving Marker Positions/\@section マーカー位置の移動/' -i markers-ja.texi;
	perl -pe 's/\@section The Mark/\@section マーク/' -i markers-ja.texi;
	perl -pe 's/\@section The Region/\@section リージョン/' -i markers-ja.texi;
	;;
    text-ja.texi)
	perl -pe 's/\@chapter Text/\@chapter テキスト/' -i text-ja.texi;
	perl -pe 's/\@section Examining Text Near Point/\@section ポイント周辺のテキストを調べる/' -i text-ja.texi;
	perl -pe 's/\@section Examining Buffer Contents/\@section バッファーのコンテンツを調べる/' -i text-ja.texi;
	perl -pe 's/\@section Comparing Text/\@section テキストの比較/' -i text-ja.texi;
	perl -pe 's/\@section Inserting Text/\@section テキストの挿入/' -i text-ja.texi;
	perl -pe 's/\@section User-Level Insertion Commands/\@section ユーザーレベルの挿入コマンド/' -i text-ja.texi;
	perl -pe 's/\@section Deleting Text/\@section テキストの削除/' -i text-ja.texi;
	perl -pe 's/\@section User-Level Deletion Commands/\@section ユーザーレベルの削除コマンド/' -i text-ja.texi;
	perl -pe 's/\@section The Kill Ring/\@section killリング/' -i text-ja.texi;
	perl -pe 's/\@subsection Kill Ring Concepts/\@subsection killリングの概念/' -i text-ja.texi;
	perl -pe 's/\@subsection Functions for Killing/\@subsection killリングのための関数/' -i text-ja.texi;
	perl -pe 's/\@subsection Yanking/\@subsection yank/' -i text-ja.texi;
	perl -pe 's/\@subsection Functions for Yanking/\@subsection yankのための関数/' -i text-ja.texi;
	perl -pe 's/\@subsection Low-Level Kill Ring/\@subsection 低レベルのkillリング/' -i text-ja.texi;
	perl -pe 's/\@subsection Internals of the Kill Ring/\@subsection killリングの内部/' -i text-ja.texi;
	perl -pe 's/\@section Undo/\@section アンドゥ/' -i text-ja.texi;
	perl -pe 's/\@section Maintaining Undo Lists/\@section アンドゥリストの保守/' -i text-ja.texi;
	perl -pe 's/\@section Filling/\@section fill/' -i text-ja.texi;
	perl -pe 's/\@section Margins for Filling/\@section fillのマージン/' -i text-ja.texi;
	perl -pe 's/\@section Adaptive Fill Mode/\@section Adaptive Fillモード/' -i text-ja.texi;
	perl -pe 's/\@section Auto Filling/\@section オートfill/' -i text-ja.texi;
	perl -pe 's/\@section Sorting Text/\@section テキストのソート/' -i text-ja.texi;
	perl -pe 's/\@section Counting Columns/\@section 列を数える/' -i text-ja.texi;
	perl -pe 's/\@section Indentation/\@section インデント/' -i text-ja.texi;
	perl -pe 's/\@subsection Indentation Primitives/\@subsection インデント用のプリミティブ/' -i text-ja.texi;
	perl -pe 's/\@subsection Indentation Controlled by Major Mode/\@subsection メジャーモードが制御するインデント/' -i text-ja.texi;
	perl -pe 's/\@subsection Indenting an Entire Region/\@subsection リージョン全体のインデント/' -i text-ja.texi;
	perl -pe 's/\@subsection Indentation Relative to Previous Lines/\@subsection 前行に相対的なインデント/' -i text-ja.texi;
	perl -pe "s/\@subsection Adjustable \`\`Tab Stops\'\'/\@subsection 調整可能な\`\`タブストップ\'\'/" -i text-ja.texi;
	perl -pe 's/\@subsection Indentation-Based Motion Commands/\@subsection インデントにもとづくモーションコマンド/' -i text-ja.texi;
	perl -pe 's/\@section Case Changes/\@section 大文字小文字の変更/' -i text-ja.texi;
	perl -pe 's/\@section Text Properties/\@section テキストのプロパティ/' -i text-ja.texi;
	perl -pe 's/\@subsection Examining Text Properties/\@subsection テキストプロパティを調べる/' -i text-ja.texi;
	perl -pe 's/\@subsection Changing Text Properties/\@subsection テキストプロパティの変更/' -i text-ja.texi;
	perl -pe 's/\@subsection Text Property Search Functions/\@subsection テキストプロパティの検索関数/' -i text-ja.texi;
	perl -pe 's/\@subsection Properties with Special Meanings/\@subsection 特殊な意味をもつプロパティ/' -i text-ja.texi;
	perl -pe 's/\@subsection Formatted Text Properties/\@subsection フォーマットされたテキストプロパティ/' -i text-ja.texi;
	perl -pe 's/\@subsection Stickiness of Text Properties/\@subsection テキストプロパティの粘着性/' -i text-ja.texi;
	perl -pe 's/\@subsection Lazy Computation of Text Properties/\@subsection テキストプロパティのlazyな計算/' -i text-ja.texi;
	perl -pe 's/\@subsection Defining Clickable Text/\@subsection クリック可能なテキストの定義/' -i text-ja.texi;
	perl -pe 's/\@subsection Defining and Using Fields/\@subsection フィールドの定義と使用/' -i text-ja.texi;
	perl -pe 's/\@subsection Why Text Properties are not Intervals/\@subsection なぜテキストプロパティはインターバルではないのか/' -i text-ja.texi;
	perl -pe 's/\@section Substituting for a Character Code/\@section 文字コードの置き換え/' -i text-ja.texi;
	perl -pe 's/\@section Registers/\@section レジスター/' -i text-ja.texi;
	perl -pe 's/\@section Transposition of Text/\@section テキストの交換/' -i text-ja.texi;
	perl -pe 's/\@section Dealing With Compressed Data/\@section 圧縮されたデータの処理/' -i text-ja.texi;
	perl -pe 's/\@section Base 64 Encoding/\@section Base 64エンコーディング/' -i text-ja.texi;
	perl -pe 's/\@section Checksum\/Hash/\@section チェックサムとハッシュ/' -i text-ja.texi;
	perl -pe 's/\@section Parsing HTML and XML/\@section HTMLとXMLの解析/' -i text-ja.texi;
	perl -pe 's/\@section Atomic Change Groups/\@section グループのアトミックな変更/' -i text-ja.texi;
	perl -pe 's/\@section Change Hooks/\@section フックの変更/' -i text-ja.texi;
	;;
    nonascii-ja.texi)
	perl -pe 's/\@chapter Non-\@acronym\{ASCII\} Characters/\@chapter 非\@acronym\{ASCII\}文字/' -i nonascii-ja.texi;
	perl -pe 's/\@section Text Representations/\@section テキストの表現方法/' -i nonascii-ja.texi;
	perl -pe 's/\@section Disabling Multibyte Characters/\@section マルチバイト文字の無効化/' -i nonascii-ja.texi;
	perl -pe 's/\@section Converting Text Representations/\@section テキスト表現の変換/' -i nonascii-ja.texi;
	perl -pe 's/\@section Selecting a Representation/\@section 表現の選択/' -i nonascii-ja.texi;
	perl -pe 's/\@section Character Codes/\@section 文字コード/' -i nonascii-ja.texi;
	perl -pe 's/\@section Character Properties/\@section 文字のプロパティ/' -i nonascii-ja.texi;
	perl -pe 's/\@section Character Sets/\@section 文字セット/' -i nonascii-ja.texi;
	perl -pe 's/\@section Scanning for Character Sets/\@section 文字セットのスキャン/' -i nonascii-ja.texi;
	perl -pe 's/\@section Translation of Characters/\@section 文字の変換/' -i nonascii-ja.texi;
	perl -pe 's/\@section Coding Systems/\@section コーディングシステム/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Basic Concepts of Coding Systems/\@subsection コーディングシステムの基本概念/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Encoding and I\/O/\@subsection エンコーディングとI\/O/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Coding Systems in Lisp/\@subsection Lispでのコーディングシステム/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection User-Chosen Coding Systems/\@subsection ユーザー選択のコーディングシステム/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Default Coding Systems/\@subsection デフォルトのコーディングシステム/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Specifying a Coding System for One Operation/\@subsection 単一の操作にたいするコーディングシステムの指定/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Explicit Encoding and Decoding/\@subsection 明示的なエンコードとデコード/' -i nonascii-ja.texi;
	perl -pe 's/\@subsection Terminal I\/O Encoding/\@subsection 端末I\/Oのエンコーディング/' -i nonascii-ja.texi;
	perl -pe 's/\@section Input Methods/\@section 入力メソッド/' -i nonascii-ja.texi;
	perl -pe 's/\@section Locales/\@section locale/' -i nonascii-ja.texi;
	;;
    searching-ja.texi)
	perl -pe 's/\@chapter Searching and Matching/\@chapter 検索とマッチング/' -i searching-ja.texi;
	perl -pe 's/\@section Searching for Strings/\@section 文字列の検索/' -i searching-ja.texi;
	perl -pe 's/\@section Searching and Case/\@section 検索と大文字小文字/' -i searching-ja.texi;
	perl -pe 's/\@section Regular Expressions/\@section 正規表現/' -i searching-ja.texi;
	perl -pe 's/\@subsection Syntax of Regular Expressions/\@subsection 正規表現の構文/' -i searching-ja.texi;
	perl -pe 's/\@subsubsection Special Characters in Regular Expressions/\@subsubsection 正規表現内の特殊文字/' -i searching-ja.texi;
	perl -pe 's/\@subsubsection Character Classes/\@subsubsection 文字クラス/' -i searching-ja.texi;
	perl -pe 's/\@subsubsection Backslash Constructs in Regular Expressions/\@subsubsection 正規表現内のバッククラッシュ構造/' -i searching-ja.texi;
	perl -pe 's/\@subsection Complex Regexp Example/\@subsection 正規表現の複雑な例/' -i searching-ja.texi;
	perl -pe 's/\@subsection Regular Expression Functions/\@subsection 正規表現の関数/' -i searching-ja.texi;
	perl -pe 's/\@section Regular Expression Searching/\@section 正規表現の検索/' -i searching-ja.texi;
	perl -pe 's/\@section POSIX Regular Expression Searching/\@section POSIX正規表現の検索/' -i searching-ja.texi;
	perl -pe 's/\@section The Match Data/\@section マッチデータ/' -i searching-ja.texi;
	perl -pe 's/\@subsection Replacing the Text that Matched/\@subsection マッチしたテキストの置換/' -i searching-ja.texi;
	perl -pe 's/\@subsection Simple Match Data Access/\@subsection 単純なマッチデータへのアクセス/' -i searching-ja.texi;
	perl -pe 's/\@subsection Accessing the Entire Match Data/\@subsection マッチデータ全体へのアクセス/' -i searching-ja.texi;
	perl -pe 's/\@subsection Saving and Restoring the Match Data/\@subsection マッチデータの保存とリストア/' -i searching-ja.texi;
	perl -pe 's/\@section Search and Replace/\@section 検索と置換/' -i searching-ja.texi;
	perl -pe 's/\@section Standard Regular Expressions Used in Editing/\@section 編集で使用される標準的な正規表現/' -i searching-ja.texi;
	;;
    syntax-ja.texi)
	perl -pe 's/\@chapter Syntax Tables/\@chapter 構文テーブル/' -i syntax-ja.texi;
	perl -pe 's/\@section Syntax Table Concepts/\@section 構文テーブルの概念/' -i syntax-ja.texi;
	perl -pe 's/\@section Syntax Descriptors/\@section 構文記述子/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Table of Syntax Classes/\@subsection 構文クラスのテーブル/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Syntax Flags/\@subsection 構文フラグ/' -i syntax-ja.texi;
	perl -pe 's/\@section Syntax Table Functions/\@section 構文テーブルの関数/' -i syntax-ja.texi;
	perl -pe 's/\@section Syntax Properties/\@section 構文プロパティ/' -i syntax-ja.texi;
	perl -pe 's/\@section Motion and Syntax/\@section モーションと構文/' -i syntax-ja.texi;
	perl -pe 's/\@section Parsing Expressions/\@section 式のパース/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Motion Commands Based on Parsing/\@subsection パースにもとづくモーションコマンド/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Finding the Parse State for a Position/\@subsection ある位置のパース状態を調べる/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Parser State/\@subsection パーサー状態/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Low-Level Parsing/\@subsection 低レベルのパース/' -i syntax-ja.texi;
	perl -pe 's/\@subsection Parameters to Control Parsing/\@subsection パースを制御するためのパラメーター/' -i syntax-ja.texi;
	perl -pe 's/\@section Syntax Table Internals/\@section 構文テーブルの内部/' -i syntax-ja.texi;
	perl -pe 's/\@section Categories/\@section カテゴリー/' -i syntax-ja.texi;
	;;
    abbrevs-ja.texi)
	perl -pe 's/\@chapter Abbrevs and Abbrev Expansion/\@chapter abbrevとabbrev展開/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Abbrev Tables/\@section abbrevテーブル/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Defining Abbrevs/\@section abbrevの定義/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Saving Abbrevs in Files/\@section ファイルへのabbrevの保存/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Looking Up and Expanding Abbreviations/\@section 略語の照会と展開/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Standard Abbrev Tables/\@section 標準的なabbrevテーブル/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Abbrev Properties/\@section abbrevプロパティー/' -i abbrevs-ja.texi;
	perl -pe 's/\@section Abbrev Table Properties/\@section abbrevテーブルのプロパティー/' -i abbrevs-ja.texi;
	;;
    processes-ja.texi)
	perl -pe 's/\@chapter Processes/\@chapter プロセス/' -i processes-ja.texi;
	perl -pe 's/\@section Functions that Create Subprocesses/\@section サブプロセスを作成する関数/' -i processes-ja.texi;
	perl -pe 's/\@section Shell Arguments/\@section shell引数/' -i processes-ja.texi;
	perl -pe 's/\@section Creating a Synchronous Process/\@section 同期プロセスの作成/' -i processes-ja.texi;
	perl -pe 's/\@section Creating an Asynchronous Process/\@section 非同期プロセスの作成/' -i processes-ja.texi;
	perl -pe 's/\@section Deleting Processes/\@section プロセスの削除/' -i processes-ja.texi;
	perl -pe 's/\@section Process Information/\@section プロセスの情報/' -i processes-ja.texi;
	perl -pe 's/\@section Sending Input to Processes/\@section プロセスへの入力の送信/' -i processes-ja.texi;
	perl -pe 's/\@section Sending Signals to Processes/\@section プロセスへのシグナルの送信/' -i processes-ja.texi;
	perl -pe 's/\@section Receiving Output from Processes/\@section プロセスからの出力の受信/' -i processes-ja.texi;
	perl -pe 's/\@subsection Process Buffers/\@subsection プロセスのバッファー/' -i processes-ja.texi;
	perl -pe 's/\@subsection Process Filter Functions/\@subsection プロセスのフィルター関数/' -i processes-ja.texi;
	perl -pe 's/\@subsection Decoding Process Output/\@subsection プロセス出力のデコード/' -i processes-ja.texi;
	perl -pe 's/\@subsection Accepting Output from Processes/\@subsection プロセスからの出力を受け入れる/' -i processes-ja.texi;
	perl -pe 's/\@section Sentinels\: Detecting Process Status Changes/\@section センチネル\: プロセス状態の変更の検知/' -i processes-ja.texi;
	perl -pe 's/\@section Querying Before Exit/\@section exit前の問い合わせ/' -i processes-ja.texi;
	perl -pe 's/\@section Accessing Other Processes/\@section 別のプセスへのアクセス/' -i processes-ja.texi;
	perl -pe 's/\@section Transaction Queues/\@section トランザクションキュー/' -i processes-ja.texi;
	perl -pe 's/\@section Network Connections/\@section ネットワーク接続/' -i processes-ja.texi;
	perl -pe 's/\@section Network Servers/\@section ネットワークサーバー/' -i processes-ja.texi;
	perl -pe 's/\@section Datagrams/\@section データグラム/' -i processes-ja.texi;
	perl -pe 's/\@section Low-Level Network Access/\@section 低レベルのネットワークアクセス/' -i processes-ja.texi;
	perl -pe 's/\@subsection \@code\{make-network-process\}/\@subsection \@code\{make-network-process\}/' -i processes-ja.texi;
	perl -pe 's/\@subsection Network Options/\@subsection ネットワークのオプション/' -i processes-ja.texi;
	perl -pe 's/\@subsection Testing Availability of Network Features/\@subsection ネットワーク機能の可用性のテスト/' -i processes-ja.texi;
	perl -pe 's/\@section Misc Network Facilities/\@section その他のネットワーク機能/' -i processes-ja.texi;
	perl -pe 's/\@section Communicating with Serial Ports/\@section シリアルポートとの対話/' -i processes-ja.texi;
	perl -pe 's/\@section Packing and Unpacking Byte Arrays/\@section バイト配列のpackとunpack/' -i processes-ja.texi;
	perl -pe 's/\@subsection Describing Data Layout/\@subsection データレイアウトの記述/' -i processes-ja.texi;
	perl -pe 's/\@subsection Functions to Unpack and Pack Bytes/\@subsection バイトのunpackとpackのための関数/' -i processes-ja.texi;
	perl -pe 's/\@subsection Examples of Byte Unpacking and Packing/\@subsection バイトのunpackとpackの例/' -i processes-ja.texi;
	;;
    display-ja.texi)
	perl -pe 's/\@chapter Emacs Display/\@chapter Emacsのディスプレー表示/' -i display-ja.texi;
	perl -pe 's/\@section Refreshing the Screen/\@section スクリーンのリフレッシュ/' -i display-ja.texi;
	perl -pe 's/\@section Forcing Redisplay/\@section 強制的な再表示/' -i display-ja.texi;
	perl -pe 's/\@section Truncation/\@section 切り詰め/' -i display-ja.texi;
	perl -pe 's/\@section The Echo Area/\@section エコーエリア/' -i display-ja.texi;
	perl -pe 's/\@subsection Displaying Messages in the Echo Area/\@subsection エコーエリアへのメッセージの表示/' -i display-ja.texi;
	perl -pe 's/\@subsection Reporting Operation Progress/\@subsection 処理の進捗レポート/' -i display-ja.texi;
	perl -pe 's/\@subsection Logging Messages in \@file\{\*Messages\*\}/\@subsection \@file\{\*Messages\*\}へのメッセージのロギング/' -i display-ja.texi;
	perl -pe 's/\@subsection Echo Area Customization/\@subsection エコーエリアのカスタマイズ/' -i display-ja.texi;
	perl -pe 's/\@section Reporting Warnings/\@section 警告のレポート/' -i display-ja.texi;
	perl -pe 's/\@subsection Warning Basics/\@subsection 警告の基礎/' -i display-ja.texi;
	perl -pe 's/\@subsection Warning Variables/\@subsection 警告のための変数/' -i display-ja.texi;
	perl -pe 's/\@subsection Warning Options/\@subsection 警告のためのオプション/' -i display-ja.texi;
	perl -pe 's/\@subsection Delayed Warnings/\@subsection 遅延された警告/' -i display-ja.texi;
	perl -pe 's/\@section Invisible Text/\@section 不可視のテキスト/' -i display-ja.texi;
	perl -pe 's/\@section Selective Display/\@section 選択的な表示/' -i display-ja.texi;
	perl -pe 's/\@section Temporary Displays/\@section 一時的な表示/' -i display-ja.texi;
	perl -pe 's/\@section Overlays/\@section オーバーレイ/' -i display-ja.texi;
	perl -pe 's/\@subsection Managing Overlays/\@subsection オーバーレイの管理/' -i display-ja.texi;
	perl -pe 's/\@subsection Overlay Properties/\@subsection オーバーレイのプロパティ/' -i display-ja.texi;
	perl -pe 's/\@subsection Searching for Overlays/\@subsection オーバーレイにたいする検索/' -i display-ja.texi;
	perl -pe 's/\@section Size of Displayed Text/\@section 表示されるテキストのサイズ/' -i display-ja.texi;
	perl -pe 's/\@section Line Height/\@section 行の高さ/' -i display-ja.texi;
	perl -pe 's/\@section Faces/\@section フェイス/' -i display-ja.texi;
	perl -pe 's/\@subsection Face Attributes/\@subsection フェイスの属性/' -i display-ja.texi;
	perl -pe 's/\@subsection Defining Faces/\@subsection フェイスの定義/' -i display-ja.texi;
	perl -pe 's/\@subsection Face Attribute Functions/\@subsection フェイス属性のための関数/' -i display-ja.texi;
	perl -pe 's/\@subsection Displaying Faces/\@subsection フェイスの表示/' -i display-ja.texi;
	perl -pe 's/\@subsection Face Remapping/\@subsection フェイスのリマップ/' -i display-ja.texi;
	perl -pe 's/\@subsection Functions for Working with Faces/\@subsection フェイスを処理するための関数/' -i display-ja.texi;
	perl -pe 's/\@subsection Automatic Face Assignment/\@subsection フェイスの自動割り当て/' -i display-ja.texi;
	perl -pe 's/\@subsection Basic Faces/\@subsection 基本的なフェイス/' -i display-ja.texi;
	perl -pe 's/\@subsection Font Selection/\@subsection フォントの選択/' -i display-ja.texi;
	perl -pe 's/\@subsection Looking Up Fonts/\@subsection フォントの照会/' -i display-ja.texi;
	perl -pe 's/\@subsection Fontsets/\@subsection フォントセット/' -i display-ja.texi;
	perl -pe 's/\@subsection Low-Level Font Representation/\@subsection 低レベルのフォント表現/' -i display-ja.texi;
	perl -pe 's/\@section Fringes/\@section フリンジ/' -i display-ja.texi;
	perl -pe 's/\@subsection Fringe Size and Position/\@subsection フリンジのサイズと位置/' -i display-ja.texi;
	perl -pe 's/\@subsection Fringe Indicators/\@subsection フリンジのインジケーター/' -i display-ja.texi;
	perl -pe 's/\@subsection Fringe Cursors/\@subsection フリンジのカーソルFringe Cursors/' -i display-ja.texi;
	perl -pe 's/\@subsection Fringe Bitmaps/\@subsection フリンジのビットマップ/' -i display-ja.texi;
	perl -pe 's/\@subsection Customizing Fringe Bitmaps/\@subsection フリンジビットマップのカスタマイズ/' -i display-ja.texi;
	perl -pe 's/\@subsection The Overlay Arrow/\@subsection オーバーレイ矢印/' -i display-ja.texi;
	perl -pe 's/\@section Scroll Bars/\@section スクロールバー/' -i display-ja.texi;
	perl -pe 's/\@section Window Dividers/\@section ウィンドウディバイダー/' -i display-ja.texi;
	perl -pe 's/\@section The \@code\{display\} Property/\@section \@code\{display\}プロパティ/' -i display-ja.texi;
	perl -pe 's/\@subsection Display Specs That Replace The Text/\@subsection テキストを置換するディスプレー仕様/' -i display-ja.texi;
	perl -pe 's/\@subsection Specified Spaces/\@subsection スペースの指定/' -i display-ja.texi;
	perl -pe 's/\@subsection Pixel Specification for Spaces/\@subsection スペースにたいするピクセル指定/' -i display-ja.texi;
	perl -pe 's/\@subsection Other Display Specifications/\@subsection その他のディスプレー仕様/' -i display-ja.texi;
	perl -pe 's/\@subsection Displaying in the Margins/\@subsection マージン内への表示/' -i display-ja.texi;
	perl -pe 's/\@section Images/\@section イメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection Image Formats/\@subsection イメージのフォーマット/' -i display-ja.texi;
	perl -pe 's/\@subsection Image Descriptors/\@subsection イメージのディスクリプタ/' -i display-ja.texi;
	perl -pe 's/\@subsection XBM Images/\@subsection XBMイメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection XPM Images/\@subsection XPMイメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection PostScript Images/\@subsection PostScriptイメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection ImageMagick Images/\@subsection ImageMagickイメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection Other Image Types/\@subsection その他のイメージタイプ/' -i display-ja.texi;
	perl -pe 's/\@subsection Defining Images/\@subsection イメージの定義/' -i display-ja.texi;
	perl -pe 's/\@subsection Showing Images/\@subsection イメージの表示/' -i display-ja.texi;
	perl -pe 's/\@subsection Multi-Frame Images/\@subsection マルチフレームのイメージ/' -i display-ja.texi;
	perl -pe 's/\@subsection Image Cache/\@subsection イメージキャッシュ/' -i display-ja.texi;
	perl -pe 's/\@section Buttons/\@section ボタン/' -i display-ja.texi;
	perl -pe 's/\@subsection Button Properties/\@subsection ボタンのプロパティ/' -i display-ja.texi;
	perl -pe 's/\@subsection Button Types/\@subsection ボタンのタイプ/' -i display-ja.texi;
	perl -pe 's/\@subsection Making Buttons/\@subsection ボタンの作成/' -i display-ja.texi;
	perl -pe 's/\@subsection Manipulating Buttons/\@subsection ボタンの操作/' -i display-ja.texi;
	perl -pe 's/\@subsection Button Buffer Commands/\@subsection ボタンのためのバッファーコマンド/' -i display-ja.texi;
	perl -pe 's/\@section Abstract Display/\@section 抽象的なディスプレー/' -i display-ja.texi;
	perl -pe 's/\@subsection Abstract Display Functions/\@subsection 抽象ディスプレーの関数/' -i display-ja.texi;
	perl -pe 's/\@subsection Abstract Display Example/\@subsection 抽象ディスプレーの例/' -i display-ja.texi;
	perl -pe 's/\@section Blinking Parentheses/\@section カッコの点滅/' -i display-ja.texi;
	perl -pe 's/\@section Character Display/\@section 文字の表示/' -i display-ja.texi;
	perl -pe 's/\@subsection Usual Display Conventions/\@subsection 通常の表示の慣習/' -i display-ja.texi;
	perl -pe 's/\@subsection Display Tables/\@subsection ディスプレーテーブル/' -i display-ja.texi;
	perl -pe 's/\@subsection Active Display Table/\@subsection アクティブなディスプレーテーブル/' -i display-ja.texi;
	perl -pe 's/\@subsection Glyphs/\@subsection グリフ/' -i display-ja.texi;
	perl -pe 's/\@subsection Glyphless Character Display/\@subsection グリフ文字の表示/' -i display-ja.texi;
	perl -pe 's/\@section Beeping/\@section ビープ/' -i display-ja.texi;
	perl -pe 's/\@section Window Systems/\@section ウィンドウシステム/' -i display-ja.texi;
	perl -pe 's/\@section Bidirectional Display/\@section 双方向テキストの表示/' -i display-ja.texi;
	;;
    os-ja.texi)
	perl -pe 's/\@chapter Operating System Interface/\@chapter オペレーティングシステムのインターフェース/' -i os-ja.texi;
	perl -pe 's/\@section Starting Up Emacs/\@section Emacsのスタートアップ/' -i os-ja.texi;
	perl -pe 's/\@subsection Summary: Sequence of Actions at Startup/\@subsection 要約: スタートアップ時のアクション順序/' -i os-ja.texi;
	perl -pe 's/\@subsection The Init File/\@subsection initファイル/' -i os-ja.texi;
	perl -pe 's/\@subsection Terminal-Specific Initialization/\@subsection 端末固有の初期化/' -i os-ja.texi;
	perl -pe 's/\@subsection Command-Line Arguments/\@subsection コマンドライン引数/' -i os-ja.texi;
	perl -pe 's/\@section Getting Out of Emacs/\@section Emacsからの脱出/' -i os-ja.texi;
	perl -pe 's/\@subsection Killing Emacs/\@subsection Emacsのkill/' -i os-ja.texi;
	perl -pe 's/\@subsection Suspending Emacs/\@subsection Emacsのサスペンド/' -i os-ja.texi;
	perl -pe 's/\@section Operating System Environment/\@section オペレーティングシステムの環境/' -i os-ja.texi;
	perl -pe 's/\@section User Identification/\@section ユーザーの識別/' -i os-ja.texi;
	perl -pe 's/\@section Time of Day/\@section 時刻/' -i os-ja.texi;
	perl -pe 's/\@section Time Conversion/\@section 時刻の変換/' -i os-ja.texi;
	perl -pe 's/\@section Parsing and Formatting Times/\@section 時刻のパースとフォーマット/' -i os-ja.texi;
	perl -pe 's/\@section Processor Run time/\@section プロセッサーの実行時間/' -i os-ja.texi;
	perl -pe 's/\@section Time Calculations/\@section 時間の計算/' -i os-ja.texi;
	perl -pe 's/\@section Timers for Delayed Execution/\@section 遅延実行のためのタイマー/' -i os-ja.texi;
	perl -pe 's/\@section Idle Timers/\@section アイドルタイマー/' -i os-ja.texi;
	perl -pe 's/\@section Terminal Input/\@section 端末の入力/' -i os-ja.texi;
	perl -pe 's/\@subsection Input Modes/\@subsection 入力のモード/' -i os-ja.texi;
	perl -pe 's/\@subsection Recording Input/\@subsection 入力の記録/' -i os-ja.texi;
	perl -pe 's/\@section Terminal Output/\@section 端末の出力/' -i os-ja.texi;
	perl -pe 's/\@section Sound Output/\@section サウンドの出力/' -i os-ja.texi;
	perl -pe 's/\@section Operating on X11 Keysyms/\@section X11キーシンボルの処理/' -i os-ja.texi;
	perl -pe 's/\@section Batch Mode/\@section batchモード/' -i os-ja.texi;
	perl -pe 's/\@section Session Management/\@section セッションマネージャー/' -i os-ja.texi;
	perl -pe 's/\@section Desktop Notifications/\@section デスクトップ通知/' -i os-ja.texi;
	perl -pe 's/\@section Notifications on File Changes/\@section ファイル変更による通知/' -i os-ja.texi;
	perl -pe 's/\@section Dynamically Loaded Libraries/\@section 動的にロードされるライブラリー/' -i os-ja.texi;
	;;
    package-ja.texi)
	perl -pe 's/\@chapter Preparing Lisp code for distribution/\@chapter 配布用 Lispコードの準備/' -i package-ja.texi;
	perl -pe 's/\@section Packaging Basics/\@section パッケージ化の基礎/' -i package-ja.texi;
	perl -pe 's/\@section Simple Packages/\@section 単純なパッケージ/' -i package-ja.texi;
	perl -pe 's/\@section Multi-file Packages/\@section 複数ファイルのパッケージ/' -i package-ja.texi;
	perl -pe 's/\@section Creating and Maintaining Package Archives/\@section パッケージアーカイブの作成と保守/' -i package-ja.texi;
	;;
    anti-ja.texi)
	perl -pe 's/\@appendix Emacs 23 Antinews/\@appendix Emacs 23のアンチニュース/' -i anti-ja.texi;
	perl -pe 's/\@section Old Lisp Features in Emacs 23/\@section Emacs 23の古い機能/' -i anti-ja.texi;
	;;
    tips-ja.texi)
	perl -pe 's/\@appendix Tips and Conventions/\@appendix ヒントと規約/' -i tips-ja.texi;
	perl -pe 's/\@section Emacs Lisp Coding Conventions/\@section Emacs Lispコーディングの慣習/' -i tips-ja.texi;
	perl -pe 's/\@section Key Binding Conventions/\@section キーバインディングの慣習/' -i tips-ja.texi;
	perl -pe 's/\@section Emacs Programming Tips/\@section Emacsプログラミングのヒント/' -i tips-ja.texi;
	perl -pe 's/\@section Tips for Making Compiled Code Fast/\@section コンパイル済みコードを高速化ためのヒント/' -i tips-ja.texi;
	perl -pe 's/\@section Tips for Avoiding Compiler Warnings/\@section コンパイラー警告を回避するためのヒント/' -i tips-ja.texi;
	perl -pe 's/\@section Tips for Documentation Strings/\@section ドキュメント文字列のヒント/' -i tips-ja.texi;
	perl -pe 's/\@section Tips on Writing Comments/\@section コメント記述のヒント/' -i tips-ja.texi;
	perl -pe 's/\@section Conventional Headers for Emacs Libraries/\@section Emacsライブラリーのヘッダーの慣習/' -i tips-ja.texi;
	;;
    internals-ja.texi)
	perl -pe 's/\@appendix GNU Emacs Internals/\@appendix GNU Emacsの内部/' -i internals-ja.texi;
	perl -pe 's/\@section Building Emacs/\@section Emacsのビルド/' -i internals-ja.texi;
	perl -pe 's/\@section Pure Storage/\@section 純粋ストレージ/' -i internals-ja.texi;
	perl -pe 's/\@section Garbage Collection/\@section ガーベージコレクション/' -i internals-ja.texi;
	perl -pe 's/\@section Memory Usage/\@section メモリー使用量/' -i internals-ja.texi;
	perl -pe 's/\@section C Dialect/\@section C方言/' -i internals-ja.texi;
	perl -pe 's/\@section Writing Emacs Primitives/\@section Emacsプリミティブの記述/' -i internals-ja.texi;
	perl -pe 's/\@section Object Internals/\@section オブジェクトの内部/' -i internals-ja.texi;
	perl -pe 's/\@subsection Buffer Internals/\@subsection バッファーの内部/' -i internals-ja.texi;
	perl -pe 's/\@subsection Window Internals/\@subsection ウィンドウの内部/' -i internals-ja.texi;
	perl -pe 's/\@subsection Process Internals/\@subsection プロセスの内部/' -i internals-ja.texi;
	perl -pe 's/\@section C Integer Types/\@section Cの整数型/' -i internals-ja.texi;
	;;
    errors-ja.texi)
	perl -pe 's/\@appendix Standard Errors/\@appendix 標準的なエラー/' -i errors-ja.texi;
	;;
    maps-ja.texi)
	perl -pe 's/\@appendix Standard Keymaps/\@appendix 標準的なキーマップ/' -i maps-ja.texi;
	;;
    hooks-ja.texi)
	perl -pe 's/\@appendix Standard Hooks/\@appendix 標準的なフック/' -i hooks-ja.texi;
	;;
    *)
	printf "Not a subject to replace : %s\n" ${1};
	;;
esac
